### PR TITLE
Switches removed from Voltage Level local data structures before call to Network listeners

### LINKED ISSUE #2016: Switches removed from Voltage Level local data structures before call to Network listeners
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Switches are removed from Voltage Level data structures before the Network listeners are notified through the method `beforeRemoval`. Switches are still in the Network index, but queries to gather information about the switch from `beforeRemoval` methods made to the voltage level fail because they have been removed from local switches collection and its corresponding edges also have been removed from the graph.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Unit test to demonstrate the issue (fails with exception trying to obtain end nodes of a switch inside a `beforeRemoval` method):

```java
public class RemoveSwitchTest {

    private static void checkNodes(Switch sw) {
        int node1 = sw.getVoltageLevel().getNodeBreakerView().getNode1(sw.getId());
        int node2 = sw.getVoltageLevel().getNodeBreakerView().getNode1(sw.getId());
        assertTrue(node1 >= 0);
        assertTrue(node2 >= 0);
    }

    @Test
    public void nodeBreakerTest() {
        Network network = NetworkTest1Factory.create();
        Switch sw = network.getSwitch("load1Breaker1");
        checkNodes(sw);
        network.addListener(new DefaultNetworkListener() {
            @Override
            public void beforeRemoval(Identifiable identifiable) {
                if (identifiable instanceof Switch) {
                    checkNodes((Switch) identifiable);
                }
            }
        });
        sw.getVoltageLevel().getNodeBreakerView().removeSwitch(sw.getId());
    }
}
```

The stack trace of the error:
```
ERROR com.powsybl.iidm.network.impl.NetworkListenerList - com.powsybl.commons.PowsyblException: Switch load1Breaker1 not found
com.powsybl.commons.PowsyblException: Switch load1Breaker1 not found
	at com.powsybl.iidm.network.impl.NodeBreakerVoltageLevel.createSwitchNotFoundException(NodeBreakerVoltageLevel.java:591)
	at com.powsybl.iidm.network.impl.NodeBreakerVoltageLevel.getEdge(NodeBreakerVoltageLevel.java:569)
	at com.powsybl.iidm.network.impl.NodeBreakerVoltageLevel$2.getNode1(NodeBreakerVoltageLevel.java:624)
	at com.powsybl.iidm.network.impl.RemoveSwitchTest.checkNodes(RemoveSwitchTest.java:15)
	at com.powsybl.iidm.network.impl.RemoveSwitchTest$1.beforeRemoval(RemoveSwitchTest.java:29)
```

* **What is the expected behavior?**
Be able to obtain the nodes of the switch before it is removed.

* **Please tell us about your environment:**
  - PowSyBl Version: 4.8.0-SNAPSHOT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
A similar issue happens in `BusBreakerVoltageLevel`.

### PR DESCRIPTION
**Pull request by zamarrenolm**
Signed-off-by: Luma <zamarrenolm@aia.es>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Closes #2016

### CODE REVIEW

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraphListener.java [hunk 1]
```diff
@@ -24,7 +24,11 @@
 
     void edgeAdded(int e, E obj);
 
+    void edgeBeforeRemoval(int e, E obj);
+
     void edgeRemoved(int e, E obj);
 
+    void allEdgesBeforeRemoval(Collection<E> obj);
+
```
Comment (miovd) [inline math/src/main/java/com/powsybl/math/graph/UndirectedGraphListener.java:32]: Please add default implementations to prevent breaking changes

Comment (zamarrenolm) [reply math/src/main/java/com/powsybl/math/graph/UndirectedGraphListener.java]: Default implementations added
