### PR TITLE
CGMES correction: rho and alpha of PTC depend on the side where the PTC is

### LINKED ISSUE #905: Wrong conversion of PTC
* **Do you want to request a *feature* or report a *bug*?**

The conversion of symmetrical and asymmetrical PTC from CGMES to IIDM has to be reviewed. 

* **What is the current behavior?**

1) The side where the PTC is located is not taken into account. I think that it is missing because rho and alpha have to be changed when we move the PTC from side 2 to side 1 in IIDM.  

2) The computation of rho is wrong for asymmetrical PTC. In the code, we have:
double alpha = Math.atan2(dy, 1 + dx);
double rho = Math.hypot(dy, 1 + dx);

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

1) We have to introduce alpha = - alpha and rho = 1 / rho when the PTC is located on side 2.

2) We have to do:
double alpha = Math.atan2(dy, 1 + dx);
double rho = 1 / Math.hypot(dy, 1 + dx);

* **What is the motivation / use case for changing the behavior?**

IOP June wrong on TransnetBW/REN/REE and on ELES.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by MioRtia**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Fixes #905

### CODE REVIEW

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java [hunk 1]
```diff
@@ -313,33 +317,37 @@ private void fillAlphaRhoListsSymmetrical(
...
+                alphas.add(side == 1 ? alpha : -alpha);
+                rhos.add(1.0);
             }
         } else {
             for (int step = lowStep; step <= highStep; step++) {
                 int n = step - neutralStep;
                 double dy = (n * du / 2 - du0) * Math.sin(theta);
-                double alpha = 2 * Math.asin(dy);
-                double rho = 1.0;
+                double angle = 2 * Math.asin(dy);
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java]: I think it is better to leave ratio = 1.0; for a better understanding of the code.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java [hunk 2]
```diff
@@ -313,33 +317,37 @@ private void fillAlphaRhoListsSymmetrical(
...
 
                 // CGMES uses ratio to define the relationship between voltage ends while IIDM uses rho
                 // ratio and rho as complex numbers are reciprocals. Given V1 and V2 the complex voltages at end 1 and end 2 of a branch we have:
                 // V2 = V1 * rho and V2 = V1 / ratio
                 // This is why we have: rho=1/ratio and alpha=-angle
-                alphas.add(-alpha);
-                rhos.add(1 / rho);
+                double alpha = -angle;
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java]: Maybe rho = 1 / ratio ; ?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java [hunk 3]
```diff
@@ -313,33 +317,37 @@ private void fillAlphaRhoListsSymmetrical(
...
+
+                // In IIDM, all PTC must be side one
+                alphas.add(side == 1 ? alpha : -alpha);
+                rhos.add(1.0);
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java]: Prefer rho instead of 1.0

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java [hunk 4]
```diff
@@ -313,33 +317,37 @@ private void fillAlphaRhoListsSymmetrical(
...
 
-                LOG.debug("ACTUAL    n,dy,alpha,rho  {} {} {} {}", n, dy, alpha, rho);
+                LOG.debug("ACTUAL    n,dy,alpha,rho  {} {} {} {}", n, dy, alpha, 1.0);
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java]: Prefer rho instead of 1.0
