### PR TITLE
Cgmes Export: Fix multiple islands after exporting an imported UCTE case to CGMES and reloading it

### LINKED ISSUE #3755: Cgmes Export: Multiple islands after exporting an imported UCTE case to CGMES and reloading it
### Describe the current behavior

- A UCTE case is first imported into the system and successfully loaded.
- The network is then exported to CGMES format without errors.
- When the exported CGMES files are loaded again, the network appears split into multiple electrical islands

### Describe the expected behavior

After the three steps, the network was expected to remain a single connected component.

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

Issue reported in Slack. 
The issue can be reproduced using the following case:
https://github.com/powsybl/pypowsybl/blob/main/data/19700101_0000_FO4_UX1.uct

### PR DESCRIPTION
**Pull request by marqueslanauja**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #3755

**What kind of change does this PR introduce?**

**What is the current behavior?**

The network is split into multiple components after exporting an imported UCTE case to CGMES and reloading it:

- A UCTE case is first imported into the system and successfully loaded.
- The network is then exported to CGMES format without errors.
- When the exported CGMES files are loaded again, the network appears split into multiple electrical islands

The boundary terminals of the paired danglingLines were associated with different topologicalNodes.  

**What is the new behavior (if this is a feature change)?**

During the export process to CGMES, if no information about the boundary is available, the boundary terminals of the paired danglingLines are associated with the same fictitious topologicalNode. If boundary information is provided, the corresponding boundary connectivityNodeId and topologicalNodeId are selected. 

The boundary connectivityNodeId and topologicalNodeId were selected by matching the `pairingKey` of the paired danglingLines with the corresponding connectivityNode or topologicalNode `name`.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

**Review by rcourtier — DISMISSED** [review]

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java [hunk 1]
```diff
@@ -307,26 +309,75 @@ private static void writeTopologicalNodes(Network network, String cimNamespace,
...
+            // As a last resort, we create the TN in the same container of the boundary line
+            LOG.error("Boundary line {}{} is not connected to a topology node in boundaries files: EQ profile must be exported for consistent results." +
+                            " Boundary line {} is considered entirely inside voltage level {}",
+                    dl.getId(), dl.getPairingKey() != null ? " linked to X-node " + dl.getPairingKey() : "", dl.getId(), dl.getTerminal().getVoltageLevel().getId());
+            containerId = context.getNamingStrategy().getCgmesId(dl.getTerminal().getVoltageLevel());
+        }
+        String fictTopologicalNodeId = context.getNamingStrategy().getCgmesId(refTyped(dl), TOPOLOGICAL_NODE);
+        writeTopologicalNode(fictTopologicalNodeId, dl.getNameOrId() + "_NODE", containerId, baseVoltage, cimNamespace, writer, context);
+
+        return fictTopologicalNodeId;
```
Comment (colineplqt) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java]: Here I suggest using `bl` instead of `dl` now that we have `BoundaryLine`.
```suggestion
    private static String createNewTopologicalNode(BoundaryLine bl, String cimNamespace, XMLStreamWriter writer, CgmesExportContext context) throws XMLStreamException {

        String baseVoltage = context.getBaseVoltageByNominalVoltage(bl.getTerminal().getVoltageLevel().getNominalV()).getId();
        // If the EQ has also been exported, a fictitious container should have been created
        String containerId = context.getFictitiousContainerFor(b
        l);
        if (containerId == null) {
            // As a last resort, we create the TN in the same container of the boundary line
            LOG.error("Boundary line {}{} is not connected to a topology node in boundaries files: EQ profile must be exported for consistent results." +
                            " Boundary line {} is considered entirely inside voltage level {}",
                    bl.getId(), bl.getPairingKey() != null ? " linked to X-node " + bl.getPairingKey() : "", bl.getId(), bl.getTerminal().getVoltageLevel().getId());
            containerId = context.getNamingStrategy().getCgmesId(bl.getTerminal().getVoltageLevel());
        }
        String fictTopologicalNodeId = context.getNamingStrategy().getCgmesId(refTyped(bl), TOPOLOGICAL_NODE);
        writeTopologicalNode(fictTopologicalNodeId, bl.getNameOrId() + "_NODE", containerId, baseVoltage, cimNamespace, writer, context);

        return fictTopologicalNodeId;
```

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java [hunk 2]
```diff
@@ -307,26 +309,75 @@ private static void writeTopologicalNodes(Network network, String cimNamespace,
...
-            }
+        for (BoundaryLine boundaryLine : network.getBoundaryLines(BoundaryLineFilter.UNPAIRED)) {
+            writeBoundaryLineTopologicalNodes(Collections.singletonList(boundaryLine), cimNamespace, writer, context);
+        }
+
+        Set<String> pairingKeys = network.getBoundaryLineStream(BoundaryLineFilter.PAIRED).map(BoundaryLine::getPairingKey).collect(Collectors.toSet());
+        for (String pairingKey : pairingKeys) {
+            List<BoundaryLine> boundaryLineList = network.getBoundaryLineStream(BoundaryLineFilter.PAIRED).filter(boundaryLine -> pairingKey.equals(boundaryLine.getPairingKey())).toList();
+            writeBoundaryLineTopologicalNodes(boundaryLineList, cimNamespace, writer, context);
+        }
```
Comment (colineplqt) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java]: Here is a simplification that allows not going twice through the stream, but it is not necessary. 

```suggestion
        Map<String, List<BoundaryLine>> boundaryLinesByPairingKey = network.getBoundaryLineStream(BoundaryLineFilter.PAIRED).collect(Collectors.groupingBy(BoundaryLine::getPairingKey));
        for (List<BoundaryLine> boundaryLineList : boundaryLinesByPairingKey.values()) {
            writeBoundaryLineTopologicalNodes(boundaryLineList, cimNamespace, writer, context);
        }
```

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java (hunk 1 above)
Comment (colineplqt) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java]: This suggestion ends up not being very clear but I only changed the "dl" into "bl".

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java (hunk 2 above)
Comment (marqueslanauja) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java]: Done. I also took the opportunity to sort the export output to make it deterministic and applied the changes to the `EquipmentExport` class.

Comment (colineplqt) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java]: Thank you

**Comment by marqueslanauja** [comment]
> Thank you for your work! I left two suggestions but feel free to discard them.
> 
> I also wonder, but it is a bit out of the scope of this PR, what we should do in case a pairing key is null, in general. If a tie line has a null pairing key, then the code will fail. I wonder if it is the behaviour that we want and if not what else would be better.

You are right, the pairingKey can be null. I tried to solve this by using an `effectivePairingKey`, which is the `pairingKey` if it is not null and the `tieLine id` if it is null.

**Review by colineplqt — DISMISSED** [review]

**Comment by olperr1** [comment]
@marqueslanauja : could you resolve the conflicts on this PR?

**Comment by marqueslanauja** [comment]
> @marqueslanauja : could you resolve the conflicts on this PR?
Done. I had to adjust the code a bit.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java [hunk 3]
```diff
@@ -1060,17 +1059,41 @@ private static String writeBoundaryLinesConnectivityNode(List<BoundaryLine> boun
...
-            connectivityNodeId = context.getNamingStrategy().getCgmesId(refTyped(boundaryLine), CONNECTIVITY_NODE);
+            Optional<String> optionalConnectivityNodeId = findConnectivityNodeId(boundaryLineList.getFirst().getPairingKey(), context);
+            connectivityNodeId = optionalConnectivityNodeId.isPresent() ? optionalConnectivityNodeId.get() : createNewConnectivityNode(boundaryLineList, baseVoltageId, cimNamespace, writer, context);
+        }
+        return connectivityNodeId;
+    }
+
+    private static Optional<String> findConnectivityNodeId(String pairingKey, CgmesExportContext context) {
+        ReferenceDataProvider referenceDataProvider = context.getReferenceDataProvider();
+        if (referenceDataProvider == null) {
```
Comment (colineplqt) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java]: I think here you should have the same as in TP export: ignore if pairingKey is null.

```suggestion
        if (pairingKey == null || referenceDataProvider == null) {
```
