### PR TITLE
Issue 1083 ucte internal equivalent nodes

### LINKED ISSUE #1083: UCTE internal equivalent nodes lost during UCTE roundtrip
* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Currently, it is hard-coded in PowSyBl that Xnodes are "Equivalent" nodes in UCTE format, and all other nodes (inside actual countries) are "Real" nodes.
However, some files may define nodes inside a country that are tagged as "Equivalent" nodes. It is the case for example for XNodes between german areas.

This information is lost during a Convergence round trip from UCTE back to UCTE.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Following UCTE file illustrates the issue.
Initial file:
```
##C 2007.05.01
##N
##ZFR
FFFFFF11              1 0        3.96708 0.00000 0.00000 0.00000
##L
##T
##R
```
becomes after UCTE import/export:
```
##C 2007.05.01
##N
##ZFR
FFFFFF11              0 0        3.96708 0.00000 0.00000 0.00000
##L
##T
##R
```

* **What is the expected behavior?**
Equivalent nodes tag should be kept at UCTE import/export

* **What is the motivation / use case for changing the behavior?**
Current behaviour is not in line with UCTE-DEF specification.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.1.0-SNAPSHOT
  - OS Version: Linux

### PR DESCRIPTION
**Pull request by jlabous**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
fix #1083

### CODE REVIEW

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java [hunk 1]
```diff
@@ -93,6 +93,7 @@ private static void createBuses(UcteNetworkExt ucteNetwork, UcteVoltageLevel uct
                     .add();
 
             addGeographicalNameProperty(ucteNode, bus);
+            bus.setFictitious(UcteNodeStatus.EQUIVALENT.equals(ucteNode.getStatus()));
```
Comment (mathbagu) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java:96]: Replace the equals by a ==
