### PR TITLE
More robust UCTE naming strategy 

### LINKED ISSUE #3191: Conversion to UCTE format
## Describe the current behavior

According to the documentation [here](https://powsybl.readthedocs.io/projects/powsybl-core/en/latest/grid_exchange_formats/index.html) Powsybl cannot export to UCTE for an imported file in other format than UCTE.

## Describe the expected behavior

Powsybl can convert a network not in UCTE format to an UCTE formatted file.

## Describe the motivation

Powsybl need to be able to export an IIDM network imported from not UCTE file to an UCTE file.

### Naming strategy

- generate special ids for UCTE (to support the [UCTE format](https://eepublicdownloads.entsoe.eu/clean-documents/pre2015/publications/ce/otherreports/UCTE-format.pdf) rules)
- need a default naming strategy

### Mapping of new elements

Some equipments must be implemented, they are currenlty listed at the beginning of the `UcteExporter::createUcteNetwork` method and throws exception if the network has one of them:

**ThreeWindingsTransformer**
Create method `UcteExporter::convertThreeWindingsTransformer` to transform a ThreeWindingsTransformer to 1 new object `UcteThreeWindingsTransformer`. Instanciate it using the electrotechnic rules used by the NetworkModification to transform 1 `ThreeWindingsTransformer` to 3 `TwoWindingsTransformer`.

The new element `UcteThreeWindingsTransformer` is represented with:
   - 3 `UcteTransformer`
   - 1 `UcteNode`
   - 1 fictious `UcteVoltageLevel`
   - 1`UcteSubstation`

**HvdcLine**
Create method `UcteExporter::convertHvdcLine` to transform an HvdcLine to 1 new object `UcteHvdcLine`.

The new element `UcteHvdcLine` is represented with:
- 1 `UcteLine`
- 2 `UcteNode` (containing 1 load and 1 group)

**LccConverterStation**
Create method `UcteExporter::convertLccConverterStation` to transform an LccConverterStation to 1 `UcteNode`.

**VscConverterStation**
Create method `UcteExporter::convertVscConverterStation` to transform an VscConverterStation to 1 `UcteNode`.

**StaticVarCompensator**
Create method `UcteExporter::convertStaticVarCompensator` to transform a StaticVarCompensator to 1 `UcteNode`. We can use the `UcteNodeTypeCode` for the voltage regulation.

**Battery**
Create method `UcteExporter::convertBattery` to transform a Battery to 1 `UcteNode`. We can use the `UcteNodeTypeCode` for the voltage regulation. Battery can be like the generator (`convertGenerators` method)?

**ShuntCompensator**
Create method `UcteExporter::convertShuntCompensator` to transform a ShuntCompensator to .............. 

**DanglingLine**
`UcteExporter::convertDanglingLine` already exists => is it used for export? 
The current equivalence results in the creation of an `UcteLine`

**Voltage regulation rules**
  - see the UCTE format documentation
  - ? todo: to describe
  - ?

### Update the documentation
[Supported formats exchanges](https://powsybl.readthedocs.io/projects/powsybl-core/en/latest/grid_exchange_formats/index.html), in particular the array for the supported conversion formats

New page for the element equivalence between IIDM and UCTE format?

### PR DESCRIPTION
**Pull request by clementleclercRTE**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Fixes #3191 

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [X] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [X] The *Breaking Change* or *Deprecated* label has been added
- [X] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

If you have a custom UCTE naming strategy (i.e. a class implementing `com.powsybl.ucte.converter.NamingStrategy`), you should implement the following method:
- `void initializeNetwork(Network network);`

**Other information**:

By default, the "Default" naming strategy is used when exporting a network in UCTE.
If you want to use the new naming strategy, you should define the following property in your configuration:
- `ucte.export.naming-strategy`: `Counter`

### CODE REVIEW

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 1]
```diff
@@ -0,0 +1,358 @@
...
+
+        if (ucteNodeIds.containsKey(nodeId)) {
+            return ucteNodeIds.get(nodeId);
+        }
+        if (namingCounter > 9999) {
+            namingCounter = 0;
+        }
+
+        StringBuilder newNodeCode = new StringBuilder(8);
+        String newNodeId = String.format("%05d", ++namingCounter);
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:122]: It would be cleaner to have a method computing `newNodeId`. It could be reused in the other `generateUcteNodeId` method.

Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:122]: The check is against 4 digits, but the `String.format` pattern uses 5 digits.
Couldn't the condition at line 117 be `if (namingCounter > 99_999)` (5 digits instead of 4)?

Another remark about this part: if `namingCounter` is reset to 0, it may produce an invalid file (several nodes with the same id). I think throwing an exception would be safer.

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 2]
```diff
@@ -0,0 +1,358 @@
...
+                .append(orderCode);
+        while (ucteNodeIds.containsKey(newNodeId)) {
+            i++;
+            orderCode = oderCode.get(i);
+            newNodeCode.replace(7, 7, String.valueOf(orderCode));
+        }
+
+        Optional<UcteNodeCode> nodeCode = UcteNodeCode.parseUcteNodeCode(newNodeCode.toString());
+        if (!nodeCode.isPresent()) {
+            System.out.println("le code en erreur est : " + newNodeCode);
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:141]: This line should be removed:
```suggestion
```

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 3]
```diff
@@ -0,0 +1,358 @@
...
+         * <ol>
+         *   <li>Attempts to get the country from the voltage level's substation</li>
+         *   <li>Maps the country name to its corresponding UCTE code</li>
+         *   <li>Returns 'X' as fallback if no valid mapping is found</li>
+         * </ol>
+         *
+         * @param voltageLevel the voltage level from which to extract the country code
+         * @return the UCTE country code character, or 'X' if no valid country is found)
+         */
+    private static char getCountryCode(VoltageLevel voltageLevel) {
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:259]: The javadoc comment of this method is not correctly indented.

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 4]
```diff
@@ -0,0 +1,358 @@
...
+ *   <li>Convert all elements within each voltage level
+ *   <li>Convert network-level elements
+ * </ol>
+ *
+ * Each element receives a unique sequential identifier during the conversion process.
+ *
+ * @param network the network to convert
+ */
+    @Override
+    public void initialiseNetwork(Network network) {
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:54]: The javadoc comment of this method is not correctly indented.

**Review by olperr1 — CHANGES_REQUESTED** [review]

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 5]
```diff
@@ -0,0 +1,358 @@
...
+        newNodeCode
+                .append(countryCode)
+                .append(newNodeId)
+                .append(voltageLevelCode)
+                .append(orderCode);
+        while (ucteNodeIds.containsKey(newNodeId)) {
+            i++;
+            orderCode = oderCode.get(i);
+            newNodeCode.replace(7, 7, String.valueOf(orderCode));
+        }
```
[the remark this answers is not in the document]
Comment (clementleclercRTE) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:137]: yes it was a mistake. the loop need to check for newNodeCode

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java (hunk 1 above)
Comment (clementleclercRTE) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java]: i create a new function "generateIDFromCounter" for generate nodeID

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 6]
```diff
@@ -0,0 +1,232 @@
...
+        namingCounter++;
+        if (namingCounter > MAX_COUNTER) {
+            int baseNumber = (namingCounter - BASE_LETTER_OFFSET) % MODULO_VALUE;
+            char letter = (char) ('A' + ((namingCounter - BASE_LETTER_OFFSET) / MODULO_VALUE));
+            return String.format("%04d%c", baseNumber, letter);
+        }
+        return String.format("%05d", namingCounter);
+    }
+
+    private static char getUcteVoltageLevelCode(double voltage) {
```
Comment (geofjamg) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:109]: To move as a utility class in `UcteVoltageLevelCode`

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 7]
```diff
@@ -0,0 +1,232 @@
...
+
+    private UcteElementId generateUcteElementId(DanglingLine danglingLine) {
+        if (ucteElementIds.containsKey(danglingLine.getId())) {
+            return ucteElementIds.get(danglingLine.getId());
+        }
+
+        Bus bus = danglingLine.getTerminal().getBusBreakerView().getBus();
+        VoltageLevel voltageLevel = danglingLine.getTerminal().getVoltageLevel();
+
+        generateUcteNodeId(danglingLine.getPairingKey(), voltageLevel);
```
Comment (geofjamg) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:169]: pairingKey could be null, you should:
 - first try we pairing key if not null
 - otherwise use the dangling line ID

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/DefaultNamingStrategy.java [hunk 8]
```diff
@@ -33,6 +33,11 @@ public String getName() {
         return "Default";
     }
 
+    @Override
+    public void initialiseNetwork(Network network) {
```
Comment (geofjamg) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/DefaultNamingStrategy.java:37]: You can move it to an `AbstractNamingStrategy`

File: ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/CounterNamingStrategyTest.java [hunk 9]
```diff
@@ -0,0 +1,129 @@
+package com.powsybl.ucte.converter;
```
Comment (geofjamg) [inline ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/CounterNamingStrategyTest.java:1]: Add licence header

File: ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/CounterNamingStrategyTest.java [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+import com.powsybl.commons.datasource.ResourceDataSource;
+import com.powsybl.commons.datasource.ResourceSet;
+import com.powsybl.ucte.network.UcteNodeCode;
+import com.powsybl.ucte.network.UcteElementId;
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
+
+import static org.junit.jupiter.api.Assertions.*;
+
+class CounterNamingStrategyTest {
```
Comment (geofjamg) [inline ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/CounterNamingStrategyTest.java:14]: Add authorship

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java [hunk 11]
```diff
@@ -145,6 +145,8 @@ private static UcteNetwork createUcteNetwork(Network network, NamingStrategy nam
 
         UcteExporterContext context = new UcteExporterContext(namingStrategy, combinePhaseAngleRegulation);
 
+        namingStrategy.initialiseNetwork(network);
```
Comment (geofjamg) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java:148]: You can call it before just creation of the naming strategy

**Review by geofjamg — CHANGES_REQUESTED** [review]

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 12]
```diff
@@ -0,0 +1,232 @@
...
+    private UcteNodeCode processExistingUcteNodeId(String nodeId) {
+        return UcteNodeCode.parseUcteNodeCode(nodeId)
+                .map(code -> {
+                    ucteNodeIds.put(nodeId, code);
+                    return code;
+                })
+                .orElseThrow(() -> new UcteException(String.format(INVALID_NODE_CODE_ERROR, nodeId)));
+    }
+
+    private UcteNodeCode createNewUcteNodeId(String nodeId, VoltageLevel voltageLevel) {
```
[the remark this answers is not in the document]
Comment (clementleclercRTE) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:75]: i changed to directly create UcteNodeCode

**Review by geofjamg — APPROVED** [review]

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/NamingStrategy.java [hunk 13]
```diff
@@ -17,6 +17,8 @@
  */
 public interface NamingStrategy {
 
+    void initialiseNetwork(Network network);
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/NamingStrategy.java:20]: Can you rename this method to `initializeNetwork` (with a 'z', which is the US English spelling)?

**Review by olperr1 — CHANGES_REQUESTED** [review]

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 14]
```diff
@@ -0,0 +1,145 @@
...
+
+    private UcteNodeCode changeOrderCode(String busId, char orderCode) {
+        UcteNodeCode newNodeCode = UcteNodeCode.parseUcteNodeCode(busId).orElseThrow();
+        newNodeCode.setBusbar(orderCode);
+        ucteNodeIds.put(busId, newNodeCode);
+        return newNodeCode;
+    }
+
+    private UcteNodeCode createNewUcteNodeId(String busId, VoltageLevel voltageLevel, char orderCode) {
+        String newNodeId = String.format("%05d", voltageLevelCounter);
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:72]: Maybe we can use [A-Z0-9] codes instead?
We could convert the number in base 36, but I think it would be better to have the letters first instead of the digits.
(=> AAAAA to AAAAZ, AAAA0 to AAAA9, then AAAABA...)

Comment (olperr1) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:72]: (But it is not required.)

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java [hunk 15]
```diff
@@ -0,0 +1,145 @@
...
+
+    private UcteElementId generateUcteElementId(DanglingLine danglingLine) {
+        if (ucteElementIds.containsKey(danglingLine.getId())) {
+            return ucteElementIds.get(danglingLine.getId());
+        }
+
+        UcteNodeCode code1;
+        UcteNodeCode code2;
+
+        code1 = getUcteNodeCode(danglingLine.getTerminal().getBusBreakerView().getBus());
```
[the remark this answers is not in the document]
Comment (geofjamg) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:119]: This is not really an issue of the naming stratégy itself but the export. When there is no bus in the bus/breaker view we cannot export the element, but it should be handled before. We should only throw an clean exception in that case in the naming stragtegy and let this for another work (many more to come)

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java (hunk 14 above)
Comment (geofjamg) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java:72]: With numbers is ok for now. Let's see that later if one day needed.

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/util/UcteConstants.java [hunk 16]
```diff
@@ -26,4 +28,7 @@ private UcteConstants() {
     public static final String ORDER_CODE = "orderCode";
     public static final String POWER_PLANT_TYPE_PROPERTY_KEY = "powerPlantType";
     public static final int DEFAULT_POWER_LIMIT = 9999;
+    public static final String NO_UCTE_CODE_ERROR = "No UCTE code found for id: ";
+    public static final List<Character> ORDER_CODES = List.of('1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D',
+            'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
```
[the remark this answers is not in the document]
Comment (geofjamg) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/util/UcteConstants.java:33]: To remove in UcteElementId. The idea was to move it in a utility class.

File: ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteElementId.java [hunk 17]
```diff
@@ -15,8 +15,8 @@
  */
 public class UcteElementId implements Comparable<UcteElementId> {
 
-    private static final List<Character> ORDER_CODES = Arrays.asList('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D',
-        'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '_', '-', '.', ' ');
+    private static final List<Character> ORDER_CODES = List.of('1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D',
+        'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
```
[the remark this answers is not in the document]
Comment (clementleclercRTE) [reply ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteElementId.java:19]: You're right,I updated it with the correct version

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/util/UcteConstants.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (clementleclercRTE) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/util/UcteConstants.java]: I created a new UcteNetworkUtil class in ucte-network to store the ORDER_CODES list and getter method

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/NamingStrategy.java (hunk 13 above)
Comment (clementleclercRTE) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/NamingStrategy.java]: I renamed it

File: ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteCountryCode.java [hunk 18]
```diff
@@ -121,4 +125,15 @@ public static boolean isUcteCountryCode(char character) {
...
     }
 
+    public static UcteCountryCode fromVoltagelevel(VoltageLevel voltageLevel) {
+        Country country = voltageLevel.getSubstation()
+                .flatMap(Substation::getCountry)
+                .orElseThrow(() -> new UcteException("No UCTE country found for substation"));
+        try {
+            return UcteCountryCode.valueOf(country.name());
+        } catch (IllegalArgumentException e) {
+            throw new UcteException(String.format("No UCTE country found for " + country.name()));
```
[the remark this answers is not in the document]
Comment (clementleclercRTE) [reply ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteCountryCode.java]: i changed this

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java [hunk 19]
```diff
@@ -0,0 +1,84 @@
...
+    @Override
+    public UcteNodeCode getUcteNodeCode(String id) {
+        return ucteNodeIds.computeIfAbsent(id, k -> UcteNodeCode.parseUcteNodeCode(k)
+                .orElseThrow(() -> new UcteException(UcteConverterConstants.NO_UCTE_CODE_ERROR + k)));
+    }
+
+    @Override
+    public UcteNodeCode getUcteNodeCode(Bus bus) {
+        if (bus == null) {
+            throw  new PowsyblException("the bus is null");
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java:41]:
```suggestion
            throw new PowsyblException("The bus is null.");
```

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java [hunk 20]
```diff
@@ -0,0 +1,84 @@
...
+    @Override
+    public UcteElementId getUcteElementId(String id) {
+        return ucteElementIds.computeIfAbsent(id, k -> UcteElementId.parseUcteElementId(k)
+                .orElseThrow(() -> new UcteException(UcteConverterConstants.NO_UCTE_CODE_ERROR + k)));
+    }
+
+    @Override
+    public UcteElementId getUcteElementId(Switch sw) {
+        if (sw == null) {
+            throw  new PowsyblException("the bus is null");
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java:63]:
```suggestion
            throw new PowsyblException("The switch is null.");
```

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java [hunk 21]
```diff
@@ -0,0 +1,84 @@
...
+        }
+        return getUcteElementId(sw.getId());
+    }
+
+    @Override
+    public UcteElementId getUcteElementId(Branch branch) {
+        if (branch == null) {
+            throw  new PowsyblException("the bus is null");
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java:71]:
```suggestion
            throw new PowsyblException("The branch is null");
```

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java [hunk 22]
```diff
@@ -0,0 +1,84 @@
...
+        }
+        return getUcteElementId(branch.getId());
+    }
+
+    @Override
+    public UcteElementId getUcteElementId(DanglingLine danglingLine) {
+        if (danglingLine == null) {
+            throw  new PowsyblException("the bus is null");
```
Comment (olperr1) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java:79]:
```suggestion
            throw new PowsyblException("The dangling line is null.");
```

File: ucte/ucte-network/src/test/java/com/powsybl/ucte/network/util/UcteNetworkUtilTest.java [hunk 23]
```diff
@@ -0,0 +1,32 @@
...
+    @Test
+    void getOrderCodeTest() {
+        assertEquals('0', UcteNetworkUtil.getOrderCode(0));
+        assertEquals('A', UcteNetworkUtil.getOrderCode(10));
+        assertThrows(com.powsybl.ucte.network.UcteException.class, () -> {
+            UcteNetworkUtil.getOrderCode(-1);
+        });
+        assertThrows(UcteException.class, () -> {
+            UcteNetworkUtil.getOrderCode(50);
+        });
```
Comment (olperr1) [inline ucte/ucte-network/src/test/java/com/powsybl/ucte/network/util/UcteNetworkUtilTest.java:30]: This would be cleaner like this:
```suggestion
        assertThrows(UcteException.class, () -> UcteNetworkUtil.getOrderCode(-1));
        assertThrows(UcteException.class, () -> UcteNetworkUtil.getOrderCode(50));
```

File: ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteCountryCode.java [hunk 24]
```diff
@@ -121,4 +125,15 @@ public static boolean isUcteCountryCode(char character) {
...
     }
 
+    public static UcteCountryCode fromVoltagelevel(VoltageLevel voltageLevel) {
+        Country country = voltageLevel.getSubstation()
+                .flatMap(Substation::getCountry)
+                .orElseThrow(() -> new UcteException("No UCTE country found for substation"));
+        try {
+            return UcteCountryCode.valueOf(country.name());
+        } catch (IllegalArgumentException e) {
+            throw new UcteException(String.format("No UCTE country found for %s",country.name()));
```
Comment (olperr1) [inline ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteCountryCode.java:135]: To fix the checkstyle issue:

```suggestion
            throw new UcteException(String.format("No UCTE country found for %s", country.name()));
```

**Review by olperr1 — CHANGES_REQUESTED** [review]

**Review by olperr1 — APPROVED** [review]
