### PR TITLE
Psse: discard badly connected equipment and fix badly defined controlled buses

### LINKED ISSUE #3341: PSS/E import failed in case of out of service badly connected elements
### Describe the current behavior

The issue could be reproduced with a modified version of IEEE 14 test case:

```
0 / END OF GENERATOR DATA, BEGIN BRANCH DATA
    1,     2,'1 ', 0.01938, 0.05917,0.05280,   0.00,   0.00,   0.00,  0.00000,  0.00000,  0.00000,  0.00000,1,1,   0.0,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000
    1,     5,'1 ', 0.05403, 0.22304,0.04920,   0.00,   0.00,   0.00,  0.00000,  0.00000,  0.00000,  0.00000,1,1,   0.0,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000
    2,     3,'1 ', 0.04699, 0.19797,0.04380,   0.00,   0.00,   0.00,  0.00000,  0.00000,  0.00000,  0.00000,1,1,   0.0,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000
    9999,  4,'1 ', 0.05811, 0.17632,0.03400,   0.00,   0.00,   0.00,  0.00000,  0.00000,  0.00000,  0.00000,0,1,   0.0,   1,1.0000,   0,1.0000,   0,1.0000,   0,1.0000
```
The last branch is connected on from side to a 9999 bus which does not exist, BUT the status is 0 which means the branch is out of service.
PSS/E tool allows this, we had the case on a real file and it was perfectly imported in PSS/E.
PowSybl failed at validation step with such a message:
```
[main] WARN com.powsybl.psse.model.pf.PsseValidation - NonTransformerBranch: Unexpected I: 9999
[main] WARN com.powsybl.psse.model.pf.PsseValidation - PSS/E Validation end. ValidCase false
```

### Describe the expected behavior

_No response_

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by marqueslanauja**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #3341

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

Psse models with badly connected equipment are declared invalid and are not imported.
Psse model with badly defined controlled buses are also declared invalid and not imported.

**What is the new behavior (if this is a feature change)?**

Psse records with badly connected equipment are discarded, the rest of the records are imported.
Badly defined controlled buses are fixed by setting the controlled bus to 0.
We have verified that PSS/E does the same.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseValidation.java [hunk 1]
```diff
@@ -204,6 +209,18 @@ private void validateNonTransformerBranches(List<PsseNonTransformerBranch> nonTr
         checkDuplicatesLinks("NonTransformerBranch", "branches", getDuplicates(busesNonTransformerBranches));
     }
 
+    private boolean isBaldyConnectedNonTransformedBranch(PsseNonTransformerBranch nonTransformerBranch, Map<Integer, List<Integer>> buses) {
+        if (!buses.containsKey(nonTransformerBranch.getI())) {
```
Comment (geofjamg) [inline psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseValidation.java:213]: This is not conditionned by the fact the transformer is out of service. Is it on purpose ? Is it what PSS/E is doing ?

Comment (marqueslanauja) [reply psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseValidation.java:213]: Yes it is on purpose. If the bus is not well defined, PSS/E discards the record in both cases, whether the status is 0 or 1..

**Comment by marqueslanauja** [comment]
> I still have a validation issue with winding cont attribute: Transformer: 9418 6841 2 Unexpected winding1 Cont: 0

Ok. I will verify the validation

File: psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseValidation.java (hunk 1 above)
Comment (geofjamg) [reply psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseValidation.java:213]: Ok, good to known

**Comment by marqueslanauja** [comment]
> > I still have a validation issue with winding cont attribute: Transformer: 9418 6841 2 Unexpected winding1 Cont: 0
> 
> Ok. I will verify the validation

It should work now. Controlled buses must be fixed before the transformer winding cod

**Review by geofjamg — APPROVED** [review]
It works very well now on our use case. Thanks @marqueslanauja.
