### PR TITLE
Get switches and internal connections from given node

### LINKED ISSUE #1523: Get all switches connected to a node
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
To get all switches connected to a node, one needs to iterate over all the switches of its voltage level.

* **What is the expected behavior?**
Get all switches connected to a node directly with cached calculation.

* **What is the motivation / use case for changing the behavior?**
Security analysis needs to find the switches corresponding to a node. Using such a method would avoid taking too much time on this search. Besides this list is almost ready in the graph through adjacencyList, which is cached.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by flo-dup**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** 
Yes, partly: fixes #1523 

**What kind of change does this PR introduce?**
Feature

**What is the current behavior?**
To get all switches or internal connections from a node, one needs to loop over all of them

**What is the new behavior (if this is a feature change)?**
Methods are available to retrieve the switches connected to a given node and to retrieve the nodes connected with an internal connection to a given node.

**Does this PR introduce a breaking change or deprecate an API?** 
No

### CODE REVIEW

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java [hunk 1]
```diff
@@ -180,6 +181,42 @@ default int getVertexCapacity() {
...
     int getEdgeVertex1(int e);
 
+    /**
+     * Return the edge objects connected to the specified vertex.
+     * This method throws a {@link com.powsybl.commons.PowsyblException} if the vertex doesn't exist.
+     *
+     * @param v the vertex index.
+     * @return an iterable of the edge objects
+     */
+    Iterable<E> getEdgeObjects(int v);
```
Comment (geofjamg) [inline math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java:191]: For the 4 methods you added, the name is ambiguis, edges also have a "number" and also have an object associated like vertices. At first when just looking at the method name, without reading the javadoc, I misunderstand the purpose of the methods. 
Even if larger, maybe we could call it something like getEdgesConnectedToVertex, getEdgeObjectsConnectedToVertex

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java [hunk 2]
```diff
@@ -521,6 +522,34 @@ default void removeInternalConnections(int node1, int node2) {
...
+         * @throws com.powsybl.commons.PowsyblException if node is not found.
+         */
+        IntStream getNodeStreamInternalConnectedTo(int node);
+
+        /**
+         * Get the internal connections connected to the {@code node}.
+         *
+         * @throws com.powsybl.commons.PowsyblException if node is not found.
+         */
+        Iterable<Integer> getNodesInternalConnectedTo(int node);
```
Comment (geofjamg) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java:551]: I known that the API is everywhere made of Stream + Iterable to let impl optimize/lazy load data, but here the number of object returned is very small and maybe we can just return a List instead of the Iterable?

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java (hunk 1 above)
Comment (flo-dup) [reply math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java:191]: Yes indeed, it's quite ambiguous, only the s of objects differentiates it from the `getEdgeObject(int e)`. Do you think the (old) existing `getEdgeObjects(int v1, int v2)` should also be renamed to something like `getEdgeObjectsBetweenVertices(int v1, int v2)` or `getEdgeObjectsConnectingVertices(int v1, int v2)`?

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java (hunk 2 above)
Comment (flo-dup) [reply iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java:551]: Done.

**Review by geofjamg — APPROVED** [review]
