### PR TITLE
CGMES. Add functional logs

### LINKED ISSUE #1887: Functional logs for CIM-CGMES converter
* **Do you want to request a *feature* or report a *bug*?**

A feature.

* **What is the current behavior?**

We log with SLF4J. And there is a lot of logs that were useful before, during the development of the gateway. But now, it is finished and some logs should be cleaned.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

As for UCTE importer, we should add functional logs (reporters) to have a mechanism of logging compatible with micro-services architecture. Furthermore, it could be nice to clean globally the logs.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by zamarrenolm**
Signed-off-by: Luma <zamarrenolm@aia.es>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Closes #1887.

### CODE REVIEW

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java [hunk 1]
```diff
@@ -113,16 +114,21 @@ public String getFormat() {
...
+        Objects.requireNonNull(networkFactory);
+        Objects.requireNonNull(reporter);
         TripleStoreOptions options = new TripleStoreOptions();
         String sourceForIidmIds = Parameter.readString(getFormat(), p, SOURCE_FOR_IIDM_ID_PARAMETER, defaultValueConfig);
         if (sourceForIidmIds.equalsIgnoreCase(SOURCE_FOR_IIDM_ID_MRID)) {
             options.setRemoveInitialUnderscoreForIdentifiers(true);
         } else if (sourceForIidmIds.equalsIgnoreCase(SOURCE_FOR_IIDM_ID_RDFID)) {
             options.setRemoveInitialUnderscoreForIdentifiers(false);
         }
+        options.setReporter(reporter.createSubReporter("Read", "Read"));
```
Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:128]: Maybe a more comprehensive key? `CGMESTriplestore`?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java [hunk 2]
```diff
@@ -113,16 +114,21 @@ public String getFormat() {
...
         CgmesModel cgmes = CgmesModelFactory.create(ds, boundary(p), tripleStore(p), options);
-        return new Conversion(cgmes, config(ds, p), activatedPostProcessors(p), networkFactory).convert();
+        Reporter conversionReporter = reporter.createSubReporter("Conversion", "Conversion");
```
Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:130]: `CGMESConversion` as key?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java [hunk 3]
```diff
@@ -7,39 +7,41 @@
...
  */
 public class Context {
 
-    // Log messages
-    private static final String FIXED_REASON = "Fixed {}. Reason: {}";
-    private static final String INVALID_REASON = "Invalid {}. Reason: {}";
-    private static final String IGNORED_REASON = "Ignored {}. Reason: {}";
-
     public Context(CgmesModel cgmes, Config config, Network network) {
+        this(cgmes, config, network, null);
```
Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:37]: Not null, pass `Reporter.NO_OP`

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java [hunk 4]
```diff
@@ -203,69 +205,132 @@ public PropertyBags phaseTapChangerTable(String tableId) {
...
+
+    private void handleIssue(ConversionIssueCategory category, String what, String reason) {
+        if (reporter != null) {
+            reportIssue(category, what, reason);
+        }
+        logIssue(category, what, reason);
+    }
+
+    private void handleIssue(ConversionIssueCategory category, String what, Supplier<String> reason) {
+        if (LOG.isWarnEnabled() || reporter != null) {
```
Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:280]: Report in any case. In default case, reporter should be `Reporter.NO_OP` meaning no operation is done

Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:280]: Report in any case. In default case, reporter should be `Reporter.NO_OP` meaning no operation is done, reporter should **not** be null

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java [hunk 5]
```diff
@@ -7,39 +7,41 @@
...
-
     public Context(CgmesModel cgmes, Config config, Network network) {
+        this(cgmes, config, network, null);
+    }
+
+    public Context(CgmesModel cgmes, Config config, Network network, Reporter reporter) {
         this.cgmes = Objects.requireNonNull(cgmes);
         this.config = Objects.requireNonNull(config);
         this.network = Objects.requireNonNull(network);
+        this.reporter = reporter;
```
Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:44]: Add `requireNonNull`

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java [hunk 6]
```diff
@@ -116,12 +117,16 @@ public Conversion(CgmesModel cgmes, Conversion.Config config, List<CgmesImportPo
...
+        this(cgmes, config, postProcessors, networkFactory, null);
+    }
+
+    public Conversion(CgmesModel cgmes, Config config, List<CgmesImportPostProcessor> activatedPostProcessors, NetworkFactory networkFactory, Reporter reporter) {
         this.cgmes = Objects.requireNonNull(cgmes);
         this.config = Objects.requireNonNull(config);
-        this.postProcessors = Objects.requireNonNull(postProcessors);
+        this.postProcessors = Objects.requireNonNull(activatedPostProcessors);
         this.networkFactory = Objects.requireNonNull(networkFactory);
+        this.reporter = reporter;
```
Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java:129]: Add `requireNonNull`

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java [hunk 7]
```diff
@@ -116,12 +117,16 @@ public Conversion(CgmesModel cgmes, Conversion.Config config, List<CgmesImportPo
         this(cgmes, config, postProcessors, NetworkFactory.findDefault());
     }
 
-    public Conversion(CgmesModel cgmes, Conversion.Config config, List<CgmesImportPostProcessor> postProcessors,
-                      NetworkFactory networkFactory) {
+    public Conversion(CgmesModel cgmes, Conversion.Config config, List<CgmesImportPostProcessor> postProcessors, NetworkFactory networkFactory) {
+        this(cgmes, config, postProcessors, networkFactory, null);
```
Comment (miovd) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java:121]: By default, use `Reporter.NO_OP`

**Review by miovd — CHANGES_REQUESTED** [review]
Some remarks.
Please consider that Reporter is never null. By default, it is `NO_OP`, not null.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java (hunk 4 above)
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:280]: I've kept the check for the reporter being different of `Reporter.NO_OP`. The check is done to avoid calling the `reason` supplier if the resulting message will not be used (an _optimization_ introduced some time ago).

Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:280]: changed to check `reporter` against `Reporter.NO_OP`

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java (hunk 1 above)
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:128]: changed the key

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java (hunk 3 above)
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:37]: avoided null reporter

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java (hunk 5 above)
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:44]: added check

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java (hunk 6 above)
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java:129]: added

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java (hunk 7 above)
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java:121]: used no-operation reporter instead of null

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java [hunk 8]
```diff
@@ -203,69 +205,126 @@ public PropertyBags phaseTapChangerTable(String tableId) {
...
+        }
+    }
+
+    private static boolean isValidForGrouping(String what) {
+        return what.equals("SvVoltage") || what.equals("Regulating Terminal") || what.equals("EmptyVscRegulation");
+    }
+
+    private void reportIssue(ConversionIssueCategory category, String what, Supplier<String> reason) {
+        Reporter categoryReporter = issueReporters.computeIfAbsent(category, cat -> reporter.createSubReporter(cat.name(), cat.toString()));
+        // FIXME(Luma) A first approach to functional logs, report issues grouped by "what" or by "reason"
```
Comment (flo-dup) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java:293]: I'm not completely convinced we should do this grouping, or at least that way. This could be done by the functional logs viewer, but the strength of what you proposed is if there are many similar logs. Then you might want to show to the user a group of similar issues instead of the details of all issues, and the details can be looked into if he wants by unfolding this group.

Nonetheless, the title of that subReporter should then sum up the content, for instance the number of issues of that type, which is not the case here. There's some refactoring needed to do that.

**Review by flo-dup — CHANGES_REQUESTED** [review]
There's been a misunderstanding here, the reporter goal is missed out. The functional logs should contain typed values, to format them according to user standards (for instance we could think of precision of displayed value depending on its type, color displayed, link to the voltage level diagram if vl id, ...). It's also meant to be used for multilingual support, and should thus be easily translated based on the user language.

Here so far the logs are preformatted using `String.format("xxx %d %f %s", x, y, z)` and the keys are equal to the log string: `reporter.report(item, item)`. Hence the front end cannot do anything more with the log than printing them, and multilingual support is impossible.

A good way to expose those problems is to export the test case in json and look at the dictionary.

**Review by miovd — CHANGES_REQUESTED** [review]

**Comment by zamarrenolm** [comment]
> There's been a misunderstanding here, the reporter goal is missed out. The functional logs should contain typed values, to format them according to user standards (for instance we could think of precision of displayed value depending on its type, color displayed, link to the voltage level diagram if vl id, ...). It's also meant to be used for multilingual support, and should thus be easily translated based on the user language.
> 
> Here so far the logs are preformatted using `String.format("xxx %d %f %s", x, y, z)` and the keys are equal to the log string: `reporter.report(item, item)`. Hence the front end cannot do anything more with the log than printing them, and multilingual support is impossible.
> 
> A good way to expose those problems is to export the test case in json and look at the dictionary.

Your are completely right in your observations. This PR was a first effort to adapt the information about issues found during the conversion to the reporter API without making almost any change to the current code.

**Comment by miovd** [comment]
> > There's been a misunderstanding here, the reporter goal is missed out. The functional logs should contain typed values, to format them according to user standards (for instance we could think of precision of displayed value depending on its type, color displayed, link to the voltage level diagram if vl id, ...). It's also meant to be used for multilingual support, and should thus be easily translated based on the user language.
> > Here so far the logs are preformatted using `String.format("xxx %d %f %s", x, y, z)` and the keys are equal to the log string: `reporter.report(item, item)`. Hence the front end cannot do anything more with the log than printing them, and multilingual support is impossible.
> > A good way to expose those problems is to export the test case in json and look at the dictionary.
> 
> Your are completely right in your observations. This PR was a first effort to adapt the information about issues found during the conversion to the reporter API without making almost any change to the current code.

I would prefer if you start with few logs in the reporter but correctly built to be usable by an external application! Maybe you can start with the `invalid` messages for example.

**Comment by zamarrenolm** [comment]
> > > There's been a misunderstanding here, the reporter goal is missed out. The functional logs should contain typed values, to format them according to user standards (for instance we could think of precision of displayed value depending on its type, color displayed, link to the voltage level diagram if vl id, ...). It's also meant to be used for multilingual support, and should thus be easily translated based on the user language.
> > > Here so far the logs are preformatted using `String.format("xxx %d %f %s", x, y, z)` and the keys are equal to the log string: `reporter.report(item, item)`. Hence the front end cannot do anything more with the log than printing them, and multilingual support is impossible.
> > > A good way to expose those problems is to export the test case in json and look at the dictionary.
> > 
> > 
> > Your are completely right in your observations. This PR was a first effort to adapt the information about issues found during the conversion to the reporter API without making almost any change to the current code.
> 
> I would prefer if you start with few logs in the reporter but correctly built to be usable by an external application! Maybe you can start with the `invalid` messages for example.

Sure, I will refactor the change to follow that.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java [hunk 9]
```diff
@@ -113,16 +114,21 @@ public String getFormat() {
...
+        Objects.requireNonNull(networkFactory);
+        Objects.requireNonNull(reporter);
         TripleStoreOptions options = new TripleStoreOptions();
         String sourceForIidmIds = Parameter.readString(getFormat(), p, SOURCE_FOR_IIDM_ID_PARAMETER, defaultValueConfig);
         if (sourceForIidmIds.equalsIgnoreCase(SOURCE_FOR_IIDM_ID_MRID)) {
             options.setRemoveInitialUnderscoreForIdentifiers(true);
         } else if (sourceForIidmIds.equalsIgnoreCase(SOURCE_FOR_IIDM_ID_RDFID)) {
             options.setRemoveInitialUnderscoreForIdentifiers(false);
         }
+        options.setReporter(reporter.createSubReporter("CGMESTriplestore", "Read"));
```
[the remark this answers is not in the document]
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java]: `Reporter` removed from `TripleStoreOptions`.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java [hunk 10]
```diff
@@ -113,16 +114,21 @@ public String getFormat() {
...
         CgmesModel cgmes = CgmesModelFactory.create(ds, boundary(p), tripleStore(p), options);
-        return new Conversion(cgmes, config(ds, p), activatedPostProcessors(p), networkFactory).convert();
+        Reporter conversionReporter = reporter.createSubReporter("CGMESConversion", "Conversion");
+        return new Conversion(cgmes, config(ds, p), activatedPostProcessors(p), networkFactory, conversionReporter).convert();
```
[the remark this answers is not in the document]
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java]: Reporter has been moved to a parameter of `Conversion::convert`.

File: cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/FunctionalLogsTest.java [hunk 11]
```diff
@@ -0,0 +1,102 @@
...
+public class FunctionalLogsTest {
+
+    @Test
+    public void testImport() {
+        TestGridModel testCase = CgmesConformity1Catalog.microGridBaseCaseBE();
+        ReporterModel reporter = new ReporterModel("testFunctionalLogs",
+                "Test importing ${name}", Map.of("name", new TypedValue(testCase.name(), TypedValue.UNTYPED)));
+        Importers.importData("CGMES", testCase.dataSource(), null, reporter);
+
+        String expected = "+ Test importing MicroGrid-BaseCase-BE" + System.lineSeparator() +
```
[the remark this answers is not in the document]
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/FunctionalLogsTest.java]: Expected result has been moved to a resource file.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java [hunk 12]
```diff
@@ -203,69 +205,126 @@ public PropertyBags phaseTapChangerTable(String tableId) {
...
+        // FIXME(Luma) simple compound key
+        String categoryGroup = category.toString();
+        String description = "Identified issues not yet organized";
+        if (!group.isEmpty() && !group.isBlank()) {
+            categoryGroup += "_" + group;
+            description = group;
+        }
+        final String description1 = description;
+        reportersByCategoryAndGroup.computeIfAbsent(categoryGroup, cg -> categoryReporter.createSubReporter(cg, description1))
+            .report(item, item);
```
[the remark this answers is not in the document]
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java]: I've made a first implementation where I keep the previous `invalid` calls, adding a detailed report built at the source code point where the issue is first detected. 
The previous calls to `fixed, invalid, missing, ignored` simply emit a log message.
The idea will be to make reports only for relevant issues, following a similar approach to what is done in UCTE importer (minor issues are logged, relevant things are reported).

**Review by miovd — APPROVED** [review]

File: cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java [hunk 13]
```diff
@@ -23,8 +26,10 @@
  */
 public abstract class AbstractCgmesModel implements CgmesModel {
 
-    protected AbstractCgmesModel() {
+    protected AbstractCgmesModel(Reporter reporter) {
+        // FIXME(Luma) we must remove properties from here. They are not used!
         this.properties = new Properties();
+        this.reporter = reporter;
```
Comment (flo-dup) [inline cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java:32]: I'd rather not retain the reporter in an object, especially if there's only one call (or few calls) on it. You'd rather put the reporter as an argument of CgmesModel::read, I find it's easier to see what's going on with it that way... at the cost of polluting a bit the API.

A good compromise is what you did in another part of that PR, save it in an existing context object which is passed along. Unfortunately here there's no such context object.

File: cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java [hunk 14]
```diff
@@ -252,6 +257,14 @@ public void read(ReadOnlyDataSource ds) {
         CgmesOnDataSource cds = new CgmesOnDataSource(ds);
         for (String name : cds.names()) {
             LOG.info("Reading [{}]", name);
+            if (reporter != null) {
```
Comment (flo-dup) [inline cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java:260]: you can suppose the reporter is never null

**Review by flo-dup — CHANGES_REQUESTED** [review]

**Review by flo-dup — APPROVED** [review]
