### PR TITLE
Do not allow connect/disconnect to modify fictionnal breaker by default

### LINKED ISSUE #3790: Connect/disconnect default predicates not symmetrical
### Describe the current behavior

When disconnecting a connected connectable and reconnecting it, the connectable might be stuck in disconnected state.

### Describe the expected behavior

```java
connectable.disconnect();
connectable.connect();
```
should result in the same connected state as initially. If the disconnection is allowed to manipulate fictitious breakers, the connection should also.

### Describe the steps

Step 1: Disconnect a connected line connected on one side to a busbar with several breakers, the first one being a fictitious one: the fictitious breaker is opened to disconnect the line.
Step 2: Reconnect that disconnected line: the reconnection fails.

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

See AbstractConnectable.java:
https://github.com/powsybl/powsybl-core/blob/c2743867c31daadd5457f0f2034a7373b6ff4e4f/iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java#L219
https://github.com/powsybl/powsybl-core/blob/c2743867c31daadd5457f0f2034a7373b6ff4e4f/iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java#L239

And also NodeBreakerTopologyModel with a comment which does not correspond to the predicate
https://github.com/powsybl/powsybl-core/blob/c2743867c31daadd5457f0f2034a7373b6ff4e4f/iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerTopologyModel.java#L1255-L1256
https://github.com/powsybl/powsybl-core/blob/c2743867c31daadd5457f0f2034a7373b6ff4e4f/iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerTopologyModel.java#L1193

### PR DESCRIPTION
**Pull request by NathanDissoubray**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #3790 

**What kind of change does this PR introduce?**

Make connect / disconnect symmetrical by default.

**What is the current behavior?**

Disconnect can operate on fictitious breaker by default, but connect cannot.

**What is the new behavior (if this is a feature change)?**

Both disconnect and connect cannot operate on fictitious breaker by default.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No, but custom IIDM maintainers will have to slightly adapt their code

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

Custom IIDM implementations' maintainers should modify their `Connectable.disconnect()` to only change the state of the **non-fictional** breakers, instead of all the breakers.

**Other information**:

Though it is not possible to use disconnect / connect to operate on fictitious breaker by default, it is still possible to operate those by using a `SwitchPredicates` as such:
- `connectable.connect(SwitchPredicates.IS_BREAKER_OR_DISCONNECTOR)`
- `connectable.disconnect(SwitchPredicates.IS_CLOSED_BREAKER)`

### CODE REVIEW

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java [hunk 1]
```diff
@@ -24,12 +24,22 @@ public interface Connectable<I extends Connectable<I>> extends Identifiable<I> {
      */
     void remove();
 
+    /**
+     * Connects the connectable by operating real breakers and disconnectors
+     * By default, connect does not change the state of fictitious breaker. If you wish to do that, please use
+     * {@link #connect(Predicate)} with {@link com.powsybl.iidm.network.util.SwitchPredicates#IS_BREAKER_OR_DISCONNECTOR}
```
Comment (olperr1) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java]:
```suggestion
     * Connects the connectable by operating real breakers and disconnectors.<br>
     * By default, this method does not change the state of fictitious breakers. If you wish to do that, use
     * {@link #connect(Predicate)} with {@link com.powsybl.iidm.network.util.SwitchPredicates#IS_BREAKER_OR_DISCONNECTOR}.
```

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java [hunk 2]
```diff
@@ -24,12 +24,22 @@ public interface Connectable<I extends Connectable<I>> extends Identifiable<I> {
...
     boolean connect();
 
     boolean connect(Predicate<Switch> isTypeSwitchToOperate);
 
     boolean connect(Predicate<Switch> isTypeSwitchToOperate, ThreeSides side);
 
+    /**
+     * Disconnects the connectable by operating real breakers
+     * By default, disconnect does not change the state of fictitious breaker. If you wish to do that, please use
+     * {@link #disconnect(Predicate)} {@link com.powsybl.iidm.network.util.SwitchPredicates#IS_CLOSED_BREAKER}
```
Comment (olperr1) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java]:
```suggestion
     * Disconnects the connectable by operating real breakers.<br>
     * By default, this method does not change the state of fictitious breakers. If you wish to do that, use
     * {@link #disconnect(Predicate)} with {@link com.powsybl.iidm.network.util.SwitchPredicates#IS_CLOSED_BREAKER}.
```

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java [hunk 3]
```diff
@@ -24,12 +24,22 @@ public interface Connectable<I extends Connectable<I>> extends Identifiable<I> {
      */
     void remove();
 
+    /**
+     * Connects the connectable by operating real breakers and disconnectors
```
Comment (olperr1) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java]: In `AbstractConnectable`, `IS_NONFICTIONAL_BREAKER` is used. So it doesn't operate the disconnectors, right?

Comment (NathanDissoubray) [reply iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java]: Indeed, changed in 39e760d74f67
Should it operate on disconnectors too, or is this correct ?
Something like IS_NONFICTIONAL_BREAKER_OR_DISCONNECTOR (which doesn't exist as a SwitchPredicates as is)

Comment (olperr1) [reply iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Connectable.java]: No, this is correct like this.
