### PR TITLE
Fix bug in setting of bus name (issue #697)

### LINKED ISSUE #697: Bus id used to set the bus name
* **Do you want to request a *feature* or report a *bug*?**
A bug

* **What is the current behavior?**
When a bus is created, the bus name is not set correctly (the id is used as name)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Here is the unit test for reproducing the issue
```java
    @Test
    public void test() {
        Network network = NetworkFactory.create("Network", "Test");
        Substation substation = network.newSubstation()
                .setId("Substation")
                .setCountry(Country.FR)
                .add();
        VoltageLevel voltageLevel = substation.newVoltageLevel()
                .setId("VoltageLevel")
                .setNominalV(400)
                .setTopologyKind(TopologyKind.BUS_BREAKER)
                .add();
        Bus bus = voltageLevel.getBusBreakerView().newBus()
                .setId("BusId")
                .setName("BusName")
                .add();
        assertEquals("BusName", bus.getName());
    }
```

* **What is the expected behavior?**
In the previous test, getName() should return the value used in setName() (not the one used in setId())

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0-SNAPSHOT
  - OS Version: Windows

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

### PR DESCRIPTION
**Pull request by MioRtia**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix during creation of a bus

* **What is the current behavior?** (You can also link to an open issue here)
When a bus is created, `bus.getName()` returns the value entered with `setId` in the busAdder.

* **What is the new behavior (if this is a feature change)?**
When a bus is created, `bus.getName()` returns the value entered with `setName` in the busAdder if it exists, the bus ID if it does not.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
Fixes #697

### CODE REVIEW

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusAdderImpl.java [hunk 1]
```diff
@@ -33,7 +35,8 @@ protected String getTypeDescription() {
     @Override
     public ConfiguredBus add() {
         String id = checkAndGetUniqueId();
-        ConfiguredBusImpl bus = new ConfiguredBusImpl(id, voltageLevel);
+        String name = Optional.ofNullable(getName()).orElse(id);
```
Comment (mathbagu) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusAdderImpl.java]: Do you add this for non regression purpose? This is related to the issue about handling optional names

Comment (geofjamg) [reply iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusAdderImpl.java]: This is redundant with what is done in Identifiable.getId, this line could be removed, no?

Comment (MioRtia) [reply iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusAdderImpl.java]: Fixed, I didn't check if `name` was optional for `Identifiable`
