### PR TITLE
cgmes: fix voltage regulating control defined at busbar section

### LINKED ISSUE #3560: CGMES: Voltage Regulation on BusBarSection improperly imported for Bus/Branch model
### Describe the current behavior

Example case:
- Generator on 10 kV with voltage regulation enabled, 228 kV targetV at remote 225 kV BusBar Section BBS1 in TopologicalNode TN1
- BBS1 in TN1 connects only to BBS2 in TN2 via a closed retained switch
- Lines are connecting from TN2 to rest of the network

The generator is imported with voltage regulation enabled, regulating local terminal at 10 kV with 228 kV targetV, causing load flow convergence issues.

### Describe the expected behavior

to be defined:
- current practice in CGMES importer is to avoid defining fictitious equipment and instead try to find an equivalent terminal, however only one TopologicalNode is examined, other topological nodes connected via closed retained switches are ignored, but could be considered.
- the current practice may be considered flawed: in case topology is changed (switches opened or closed) the chosen terminal may not be the relevant one anymore. To solve this we could instead define a fictitious zero loads to represent busbar sections and use this fictitious load terminal to be the regulating terminal.
- or ultimately, disable the voltage control in case of failure to find a proper terminal.
- Longer term solutions could be to either add support of busbar sections model in bus/breaker topology kind (not just node/breaker), or allow configured buses to be used instead of equipment terminals

### Describe the steps

See example case.

### Environment

PowSyBl core 6.8.1

### Relevant Log Output

Could not find any relevant warning in the logs

### Extra Information

powsybl-open-loadflow users may want to change [parameter `minNominalVoltageTargetVoltageCheck`](https://powsybl.readthedocs.io/projects/powsybl-open-loadflow/en/latest/loadflow/parameters.html) from default 20 kV to 0 kV to disable the improperly imported voltage regulation and workaround the load flow convergence issue.

### PR DESCRIPTION
**Pull request by marqueslanauja**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

fixes #3560

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

When a model is imported in busBreaker level, busbar sections are not imported. As a result, voltage regulating terminals defined on busbar sections are ignored, and the voltage regulating control is localized by setting the generator terminal as the regulating terminal.

**What is the new behavior (if this is a feature change)?**

When a nodeBreaker model is imported as busBreaker and voltage regulating controls are defined on busbar sections, we attempt to identify an equivalent IIDM terminal that is connected to the busbar section through switches.

The method `RegulatingTerminalMapper.findSwitchCgmesTerminalIdForConnectivityNode` is a bit cpu intensive  but it will only be used when a nodeBreaker model is imported as busBreaker and voltage regulating terminals are defined on busbar sections

A new approach has been implemented without using the previous method (`RegulatingTerminalMapper.findSwitchCgmesTerminalIdForConnectivityNode` ). This new approach has no impact on CPU usage. The previous method has been removed.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

**Comment by jeandemanged** [comment]
Hi @marqueslanauja ,
After some testing on real data (pan-EU CGM):
- performance is an issue: time to import increases from 1'18 to 1'56. And only for 9 new regulating terminals properly identified.
- I am not sure if I understand the implemented logic well, it seems it looks only "one switch away ?" Below a picture of my real case where a regulating terminal is still not identified, causing load flow divergence. The generator on top right regulates busbar section "1.1". The disconnectors are not retained, the breakers are - in case it matters.

image


image

**Comment by marqueslanauja** [comment]
> Hi @marqueslanauja , After some testing on real data (pan-EU CGM):
> 
> * performance is an issue: time to import increases from 1'18 to 1'56. And only for 9 new regulating terminals properly identified.
> * I am not sure if I understand the implemented logic well, it seems it looks only "one switch away ?" Below a picture of my real case where a regulating terminal is still not identified, causing load flow divergence. The generator on top right regulates busbar section "1.1". The disconnectors are not retained, the breakers are - in case it matters.
> 
> image image

I've implemented a new approach. It has no impact on CPU usage. Using your Python code, I created a more complex case that I used as a unit test. Here is the diagram for the new case:

image

**Comment by jeandemanged** [comment]
> 
> I've implemented a new approach. It has no impact on CPU usage. Using your Python code, I created a more complex case that I used as a unit test. Here is the diagram for the new case:
> 

Hi @marqueslanauja ,
Many thanks on the fix, just tested now: no more performance issue, and now the missing regulating terminals are well identified, load flow converges as expected!

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java [hunk 1]
```diff
@@ -399,6 +401,17 @@ private Optional<Terminal> findBusBranch() {
         }
     }
 
+    static Optional<Terminal> findEquivalentTerminalForVoltageRegulatingTerminalDefinedAtBusbarSection(String cgmesTerminalId, Context context) {
+        CgmesTerminal busbarSectionCgmesTerminal = context.cgmes().terminal(cgmesTerminalId);
+        if (busbarSectionCgmesTerminal == null) {
+            return Optional.empty();
+        }
+        Bus busBreakerView = context.network().getBusBreakerView().getBus(busbarSectionCgmesTerminal.topologicalNode());
```
Comment (jeandemanged) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java]: misleading variable name, this is not a `Network.BusBreakerView` but a `Bus`: rename to either just `bus` or `busInBusBreakerView` ?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java [hunk 2]
```diff
@@ -399,6 +401,17 @@ private Optional<Terminal> findBusBranch() {
...
+        return busBreakerView != null
+                ? EquivalentTerminalFinderVoltageControl.best(EquivalentTerminalFinderVoltageControl.findTerminalsBusBranch(busBreakerView.getVoltageLevel(), busBreakerView))
```
Comment (jeandemanged) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java]: not sure here, my understanding is that  `findTerminalsBusBranch` does not consider opened switches ?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java (hunk 1 above)
Comment (marqueslanauja) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java]: Done

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java (hunk 2 above)
Comment (marqueslanauja) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java]: Both open and closed switches are considered. The regulating terminal is defined during the convert process, and at that point only the EQ file is considered. Switches are created as open or closed based on their normal state. Later, during the update phase, the switch statuses are updated using the SSH file

Comment (jeandemanged) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java]: Ok understood.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java [hunk 3]
```diff
@@ -42,9 +42,11 @@ public static Optional<Terminal> mapForVoltageControl(String cgmesTerminalId, Co
                         .or(() -> new EquivalentTerminalFinderVoltageControl(cgmesTerminalId, context).find())
                         // As a last resource, rely on the "find" method of terminal mapping:
                         // Bus/branch models may define remote voltage controls that point to busbar sections
-                        // Busbar sections are not mapped to IIDM
+                        // Since busbar sections are not mapped to IIDM, we look for an equivalent IIDM terminal
+                        // is connected to the busbar section via switches
```
Comment (rcourtier) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java]:
```suggestion
                        // that is connected to the busbar section via switches
```

File: cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java [hunk 4]
```diff
@@ -86,6 +89,38 @@ void microGridBaseBECaseRegulatingTerminalsDefinedOnSwitches() {
         assertEquals(21.987, regulationValue, 0.0);
     }
 
+    @Test
+    void voltageRegulatingTerminalAtBusbarSectionNodeBreakerTest() {
+        Network network = readCgmesResources("/issues/voltage-regulating-terminal-at-busbar-section",
+                "issue_3560_CGMES_EQ.xml",
+                "issue_3560_CGMES_SSH.xml",
+                "issue_3560_CGMES_SV.xml",
+                "issue_3560_CGMES_TP.xml");
```
Comment (rcourtier) [inline cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java]: SV and TP profiles are not necessary for a node-breaker import.

File: cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java [hunk 5]
```diff
@@ -86,6 +89,38 @@ void microGridBaseBECaseRegulatingTerminalsDefinedOnSwitches() {
...
+    @Test
+    void voltageRegulatingTerminalAtBusbarSectionBusBreakerTest() {
+        Properties importParams = new Properties();
+        importParams.put(CgmesImport.IMPORT_NODE_BREAKER_AS_BUS_BREAKER, "true");
+
+        Network network = readCgmesResources(importParams,
+                "/issues/voltage-regulating-terminal-at-busbar-section",
+                "issue_3560_CGMES_EQ.xml",
+                "issue_3560_CGMES_SSH.xml",
+                "issue_3560_CGMES_SV.xml",
```
Comment (rcourtier) [inline cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java]: SV profile is not required for a bus-branch import.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java (hunk 3 above)
Comment (marqueslanauja) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingTerminalMapper.java]: Done

File: cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java (hunk 4 above)
Comment (marqueslanauja) [reply cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java]: Done

File: cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java (hunk 5 above)
Comment (marqueslanauja) [reply cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java]: Done
