### PR TITLE
Fix cloning variants with already existing ids and without overwriting

### LINKED ISSUE #1593: Wrong VariantManager state when cloning a variant
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Cloning a variant into several variants may put the VariantManager in a wrong state.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
    network.getVariantManager().cloneVariant(VariantManagerConstants.INITIAL_VARIANT_ID, "s1");  
   // network.getVariantManager().getVariantArraySize() => 2
    try {
        network.getVariantManager().cloneVariant(VariantManagerConstants.INITIAL_VARIANT_ID, {"s2", "s1"}; // throws an exception while adding s1
    } catch (PowsyblException err) {
        // network.getVariantManager().getVariantArraySize() = 3 here but variants of equipments for "s2" are not allocated 
        // (because `VariantManagerImpl::allocateVariantArrayElements` was not called)
    }
```

* **What is the expected behavior?**
To be discussed : in previous example, after the exception is thrown, `network.getVariantManager().getVariantArraySize()` should return either : 
    - 2 and no more variant allocated
   - 3 and `VariantManagerImpl::allocateVariantArrayElements` is called.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by rolnico**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**
Fixes #1593

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java [hunk 1]
```diff
@@ -359,6 +360,32 @@ void overwriteVariant() {
         assertEquals(605.0, generator.getTargetP(), 0.0);
     }
 
+    @Test
+    void testOverwriteVariantOrNot() {
+        String variante1 = "v1";
+        String variante2 = "v2";
```
Comment (olperr1) [inline iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java]: Typo: "variante" -> "variant"

**Review by olperr1 — APPROVED** [review]
