### PR TITLE
fix Anonymizer within extensions 

### LINKED ISSUE #2114: Anonymizer within extensions
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Anonymizer is not used with extensions serialization.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create or import a network with an extension which contains id information, for instance `BaseVoltageMapping`
2. Export with anonymizer
3. Import (or edit) the generated file and look at the ids within the extension tag

**What is the expected behavior?**
Ids are anonymized

**What is the motivation / use case for changing the behavior?**
The extensions are of no use if the ids do not refer to anything.

### PR DESCRIPTION
**Pull request by samirromdhani**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #2114

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

To anonymize:
> #### cgmes
- [x] BaseVoltageMapping
  - Id
- [x] CgmesMetadataModel
   - Id
   - ModelingAuthoritySet
   - DependentOn
   - Supersedes
- [x] CgmesDanglingLineBoundaryNode
    - LineEnergyIdentificationCodeEic
- [x] CgmesLineBoundaryNode
   - LineEnergyIdentificationCodeEic
- [x] CgmesTapChanger
   - Id
   - ControlId
> #### iidm
- [x] Measurements
   - id
- [x] DiscreteMeasurements
    - id

### CODE REVIEW

File: cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingSerDe.java [hunk 1]
```diff
@@ -50,23 +57,29 @@ public void write(BaseVoltageMapping extension, SerializerContext context) {
...
             if (elementName.equals(BASE_VOLTAGE_ROOT_ELEMENT)) {
-                double nominalV = context.getReader().readDoubleAttribute("nominalVoltage");
-                Source sourceBV = context.getReader().readEnumAttribute("source", Source.class);
-                String baseVoltageId = context.getReader().readStringAttribute("id");
-                context.getReader().readEndNode();
+                double nominalV = reader.readDoubleAttribute("nominalVoltage");
+                Source sourceBV = reader.readEnumAttribute("source", Source.class);
+                String baseVoltageId = fromMinimumVersionOrElse(IidmVersion.V_1_16, networkContext,
+                        () -> networkContext.getAnonymizer().deanonymizeString(reader.readStringAttribute("id")),
+                        () -> reader.readStringAttribute("id"));
```
Comment (olperr1) [inline cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingSerDe.java]: Here, you can read the attribute before the test on the version.

**Review by olperr1 — CHANGES_REQUESTED** [review]
I think having a `fromMinimumVersionOrElse` method taking 2 lambdas is a bit over-complicated.
With 2 simple methods in the context classes, we can achieve the same goal:
- `String anonymizeFromMinimumVersion(String val, IidmVersion version)`
- `String deanonymizeFromMinimumVersion(String val, IidmVersion version)`
This methods should check the version to determine if the (de)anonymization should be perform on the `val` attribute and the anonymizer could be retrieve directly form the current context.


For the `read` methods:
```java
String value = reader.readStringAttribute(ATTRIBUTE);
String attribute = networkContext.deanonymizeFromMinimumVersion(value, IidmVersion.V_1_16);
```

For the `write` methods:
```java
writer.writeNodeContent(networkContext.anonymizeFromMinimumVersion(attributeValue, IidmVersion.V_1_16);
```

**Comment by samirromdhani** [comment]
> I think having a `fromMinimumVersionOrElse` method taking 2 lambdas is a bit over-complicated. With 2 simple methods in the context classes, we can achieve the same goal:
> 
> * `String anonymizeFromMinimumVersion(String val, IidmVersion version)`
> * `String deanonymizeFromMinimumVersion(String val, IidmVersion version)`
>   This methods should check the version to determine if the (de)anonymization should be perform on the `val` attribute and the anonymizer could be retrieve directly form the current context.
> 
> For the `read` methods:
> 
> ```java
> String value = reader.readStringAttribute(ATTRIBUTE);
> String attribute = networkContext.deanonymizeFromMinimumVersion(value, IidmVersion.V_1_16);
> ```
> 
> For the `write` methods:
> 
> ```java
> writer.writeNodeContent(networkContext.anonymizeFromMinimumVersion(attributeValue, IidmVersion.V_1_16);
> ```

 Thanks, this approach is simpler. I implemented it that way.

File: cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java [hunk 2]
```diff
@@ -63,4 +75,118 @@ void testLegacyDanglingLine() throws IOException {
...
+            // When Export (with anonymized option)
+            ByteArrayOutputStream os = new ByteArrayOutputStream();
+            Anonymizer anonymizer = NetworkSerDe.write(network, exportOptions, os);
+            // Then check anonymized code != original code
+            String anonymizedLineEnergyIdentificationCodeEic = anonymizer.anonymizeString("EIC_CODE");
+            assertNotEquals("EIC_CODE", anonymizedLineEnergyIdentificationCodeEic);
+            // Then check xml content (contain only anonymized code)
+            String xmlContent = os.toString(StandardCharsets.UTF_8);
+            assertTrue(xmlContent.contains("lineEnergyIdentificationCodeEic=\"" + anonymizedLineEnergyIdentificationCodeEic + "\""));
+            // Then import without anonymizer
```
Comment (olperr1) [inline cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java]: There should also be tests importing the network **with** the anonymizer.

File: cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java [hunk 3]
```diff
@@ -63,4 +75,118 @@ void testLegacyDanglingLine() throws IOException {
...
+            ExportOptions exportOptions = new ExportOptions().setVersion(version.toString(".")).setAnonymized(true);
+            // When Export (with anonymized option)
+            ByteArrayOutputStream os = new ByteArrayOutputStream();
+            Anonymizer anonymizer = NetworkSerDe.write(network, exportOptions, os);
+            String anonymizedLineEnergyIdentificationCodeEic = anonymizer.anonymizeString("EIC_CODE");
+            assertNotEquals("EIC_CODE", anonymizedLineEnergyIdentificationCodeEic);
+            // Then check xml content (contain only anonymized code)
+            String xmlContent = os.toString(StandardCharsets.UTF_8);
+            assertTrue(xmlContent.contains("lineEnergyIdentificationCodeEic=\"" + anonymizedLineEnergyIdentificationCodeEic + "\""));
+            // Then import without anonymizer
```
Comment (olperr1) [inline cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java]: Same here

File: cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesMetadataModelsTest.java [hunk 4]
```diff
@@ -84,4 +91,59 @@ void invalid() {
...
+            assertFalse(xmlContent.contains("id=\"sshId\""));
+            assertTrue(xmlContent.contains("modelingAuthoritySet=\"" + anonymizedModelingAuthoritySet + "\""));
+            assertFalse(xmlContent.contains("modelingAuthoritySet=\"RTE\""));
+            assertTrue(xmlContent.contains("dependentOnModel>" + anonymizedDependentOn1 + "<"));
+            assertFalse(xmlContent.contains("dependentOnModel>ssh-dependency1<"));
+            assertTrue(xmlContent.contains("dependentOnModel>" + anonymizedDependentOn2 + "<"));
+            assertFalse(xmlContent.contains("dependentOnModel>ssh-dependency2<"));
+            assertTrue(xmlContent.contains("supersedesModel>" + anonymizedSupersedes + "<"));
+            assertFalse(xmlContent.contains("AA SSH previous ID"));
+            //Then import without anonymizer
```
Comment (olperr1) [inline cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesMetadataModelsTest.java]: Same here

File: cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesTapChangersSerDeTest.java [hunk 5]
```diff
@@ -46,4 +56,48 @@ void test() throws IOException {
...
+            // Then check anonymized id, controlId != original values
+            String anonymizedId = anonymizer.anonymizeString("tc1");
+            String anonymizedControlId = anonymizer.anonymizeString("control1");
+            assertNotEquals("tc1", anonymizedId);
+            assertNotEquals("control1", anonymizedControlId);
+            // Then check xml content (contain only anonymized id and controlId)
+            String xmlContent = os.toString(StandardCharsets.UTF_8);
+            assertTrue(xmlContent.contains("id=\"" + anonymizedId + "\""));
+            assertTrue(xmlContent.contains("controlId=\"" + anonymizedControlId + "\""));
+            // Then import without anonymizer
```
Comment (olperr1) [inline cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesTapChangersSerDeTest.java]: Same here

File: iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/DiscreteMeasurementsXmlTest.java [hunk 6]
```diff
@@ -58,4 +62,69 @@ void test() throws IOException {
...
+            Anonymizer anonymizer = NetworkSerDe.write(network, exportOptions, os);
+            // Then check anonymized id != original ids
+            String anonymizedDiscreteMeasurementId = anonymizer.anonymizeString("discreteMeasurementId");
+            assertNotEquals("discreteMeasurementId", anonymizedDiscreteMeasurementId);
+            // Then check xml content (contain only anonymized id)
+            byte[] anonymizedXml = os.toByteArray();
+            String xmlContent = new String(anonymizedXml, StandardCharsets.UTF_8);
+            assertTrue(xmlContent.contains("id=\"" + anonymizedDiscreteMeasurementId + "\""));
+            assertFalse(xmlContent.contains("id=\"discreteMeasurementId\""));
+            //Then import without anonymizer
```
Comment (olperr1) [inline iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/DiscreteMeasurementsXmlTest.java]: Same here

File: iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/MeasurementsXmlTest.java [hunk 7]
```diff
@@ -68,4 +74,72 @@ void test() throws IOException {
...
+            ByteArrayOutputStream os = new ByteArrayOutputStream();
+            Anonymizer anonymizer = NetworkSerDe.write(network, exportOptions, os);
+            // Then check anonymized id != original id
+            String anonymizedMeasurementId = anonymizer.anonymizeString("Measurement_ID");
+            assertNotEquals("Measurement_ID", anonymizedMeasurementId);
+            // Then check xml content (contain only anonymized id)
+            String xmlContent = os.toString(StandardCharsets.UTF_8);
+            assertTrue(xmlContent.contains("id=\"" + anonymizedMeasurementId + "\""));
+            assertFalse(xmlContent.contains("id=\"Measurement_ID\""));
+            //Then import without anonymizer
```
Comment (olperr1) [inline iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/MeasurementsXmlTest.java]: Same here

File: cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java (hunk 2 above)
Comment (samirromdhani) [reply cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java]: Done

File: cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java [hunk 8]
```diff
@@ -63,4 +76,131 @@ void testLegacyDanglingLine() throws IOException {
...
+            // Then check import without anonymizer
+            Network importedNetwork1 = NetworkSerDe.read(new ByteArrayInputStream(os.toByteArray()));
+            assertWhenImportCgmesBoundaryLineBoundaryNode(importedNetwork1, anonymizer.anonymizeString("NHV1_NHV2_1"), anonymizedLineEnergyIdentificationCodeEic);
+            // Then check import with anonymizer
+            Network importedNetwork2 = NetworkSerDe.read(new ByteArrayInputStream(os.toByteArray()), new ImportOptions(), anonymizer);
+            assertWhenImportCgmesBoundaryLineBoundaryNode(importedNetwork2, "NHV1_NHV2_1", "EIC_CODE");
+        });
+    }
+
+    private void assertWhenImportCgmesBoundaryLineBoundaryNode(Network importedNetwork, String tiLineId, String identificationCodeEic) {
```
Comment (olperr1) [inline cgmes/cgmes-extensions/src/test/java/com/powsybl/cgmes/extensions/CgmesBoundaryNodeSerDeTest.java]: Typo: `tiLineId` -> `tieLineId` (the final "e" of "tie" is missing)
