### PR TITLE
Powerfactory: support ElmLodmv and ElmXnet elements

### LINKED ISSUE #2403: PowerFactory import, support ElmLodmv and ElmXnet elements
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the expected behavior?**
ElmLodmv (Medium Voltage Loads) and ElmXnet (External Grids) should be converted.

* **What is the motivation / use case for changing the behavior?**
Support more cases.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by marqueslanauja**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #2403

**What kind of change does this PR introduce?**

**What is the current behavior?**

ElmLodmv and ElmXnet are currently not supported.

**What is the new behavior (if this is a feature change)?**

 Medium-Voltage Load (ElmLodmv) and External Grid (ElmXnet) are now supported.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+
+        private static ExternalGridModel create(DataObject elmXnet) {
+
+            BusType busType = bustpToBusType(elmXnet.getStringAttributeValue("bustp"));
+
+            PQ target = calculateTargetPQ(elmXnet);
+            PQ sign = calculateSignPQ(elmXnet);
+
+            double usetpoint = elmXnet.findFloatAttributeValue("usetp").orElse(Float.NaN);
+            double referenceAngle = elmXnet.findFloatAttributeValue("phini").orElse(Float.NaN);
```
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: phiini ?

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+
+            double minP = elmXnet.getFloatAttributeValue("Pmin_uc");
```
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Active and reactive should be managed as optional

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+            double maxP = elmXnet.getFloatAttributeValue("Pmax_uc");
+            double minQ = elmXnet.getFloatAttributeValue("q_min");
```
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: q_min and qmax seems not to exist: Qmin Qmax ?
What is the difference with or cQ_min cQ_max ?

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 2 above)
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Pmin_uc or Pmin_ucPu: should be handle both ?

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java [hunk 4]
```diff
@@ -0,0 +1,188 @@
...
+            BusType busType = bustpToBusType(elmXnet.getStringAttributeValue("bustp"));
+
+            PQ target = calculateTargetPQ(elmXnet);
+            PQ sign = calculateSignPQ(elmXnet);
+
+            double usetpoint = elmXnet.findFloatAttributeValue("usetp").orElse(Float.NaN);
+            double referenceAngle = elmXnet.findFloatAttributeValue("phini").orElse(Float.NaN);
+
+            double minP = elmXnet.getFloatAttributeValue("Pmin_uc");
+            double maxP = elmXnet.getFloatAttributeValue("Pmax_uc");
```
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Is Pmax_uc exist ? Pmax_ucPu ?

**Review by geofjamg — CHANGES_REQUESTED** [review]

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 3 above)
Comment (geofjamg) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: image

Looking at the UI the fields min and max are taken from cQ_min  and cQ_max

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 2 above)
Comment (geofjamg) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: image

And here min max active power are taken from Pmin_uc and MaxS

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 1 above)
Comment (geofjamg) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: I confirm, there is 2 i

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+
+            BusType busType = bustpToBusType(elmXnet.getStringAttributeValue("bustp"));
+
+            PQ target = calculateTargetPQ(elmXnet);
+            PQ sign = calculateSignPQ(elmXnet);
+
+            double usetpoint = elmXnet.findFloatAttributeValue("usetp").orElse(Float.NaN);
+            double referenceAngle = elmXnet.findFloatAttributeValue("phiini").orElse(Float.NaN);
+
+            double minP = elmXnet.findFloatAttributeValue("Pmin_uc").orElse((float) Math.min(target.p * sign.p, 0.0));
```
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: In case of missing value I would set an infinite (or very large) value so that we get no limit in practice

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 1 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Done

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 2 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Done

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 3 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Done

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 2 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Done

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 4 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: I don’t know, I don’t have updated documentation

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 5 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Done

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+        // a negative value is considered to be a consumed active power
+        private static PQ calculateTargetPQ(DataObject elmXnet) {
+
+            Optional<Float> pgini = elmXnet.findFloatAttributeValue("pgini");
+            Optional<Float> qgini = elmXnet.findFloatAttributeValue("qgini");
+            Optional<Float> sgini = elmXnet.findFloatAttributeValue("sgini");
+            Optional<Float> cosgini = elmXnet.findFloatAttributeValue("cosgini");
+
+            PQ target;
+            if (pgini.isPresent() && qgini.isPresent()) {
```
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Maybe we should use mode_inp (if present) for that ?

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/LoadConverter.java [hunk 7]
```diff
@@ -49,10 +51,54 @@ private LoadModel(double p0, double q0) {
...
-            float q0 = elmLod.getFloatAttributeValue("qlini");
+            PQ pq = calculatePQ(elmLod);
+            PQ sign = calculateSignPQ(elmLod);
+
+            return new LoadModel(pq.p * sign.p, pq.q * sign.q);
+        }
+
+        private static PQ calculatePQ(DataObject elmLod) {
+
+            Optional<Float> plini = elmLod.findFloatAttributeValue("plini");
```
Comment (geofjamg) [inline powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/LoadConverter.java]: ElmLodmv allows to model both a load and a generation.
We should in addtion to plini, qlini, slini and coslini, import generation part pgini, qgini, sgini, cosgini
By creating  maybe a PQ generator ?

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java (hunk 6 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ExternalGridConverter.java]: Done. Since `mode_inp` is also used in `ElmLod`, I have added all the possible values I’ve found, some of them from the ElmGenStat TechRef (2010)

File: powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/LoadConverter.java (hunk 7 above)
Comment (marqueslanauja) [reply powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/LoadConverter.java]: Done. I've created a generator

**Review by geofjamg — APPROVED** [review]

**Review by zamarrenolm — APPROVED** [review]
