### PR TITLE
Psse: Fix export of disconnected buses

### LINKED ISSUE #3761: PSSE export fails when bus is disconnected
### Describe the current behavior

Reported in Slack by Roman Vykuka (2026-02-05):

_In a bus-branch topology, when a bus without any injection is connected via a disconnected line,  RAW export fails. According to validations in NodeBreakerTopologyModel and BusBreakerTopologyModel bus is considered invalid and ruled out from the topology._

### Describe the expected behavior

It would be better not to export elements leading to an invalid bus to RAW.

### Describe the steps

_No response_

### Environment

- PowSyBl 7.1.1

### Relevant Log Output

_No response_

### Extra Information

The user has provided a simple test case:

[raw-export-failing.zip](https://github.com/user-attachments/files/25122359/raw-export-failing.zip)

### PR DESCRIPTION
**Pull request by marqueslanauja**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #3761

**What kind of change does this PR introduce?**

Bug fix.

**What is the current behavior?**

When an isolated bus is exported, some terminals have no associated busView and then the export process crashes.
All nodes connected through internalConnections are exported in detailed connectivity mode.

**What is the new behavior (if this is a feature change)?**

When a model is exported without detailed connectivity, all terminals have an associated bus: a busView if it exists, or a busBreaker if the busView is null.
Only one node, the representative node, is exported per connected set through internalConnections.

Some streams have been sorted to ensure PSSE bus I identifiers are obtained deterministically.
In the generators, Q is exported as 0.0 when it is NaN.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java [hunk 1]
```diff
@@ -304,4 +304,213 @@ void exportDataTest() throws IOException {
         assertEquals("psse.export.update", psseExporter.getParameters().get(0).getName());
         assertEquals("psse.export.raw-format", psseExporter.getParameters().get(1).getName());
     }
+
+    @Test
+    void rawExportFailingTest() throws IOException {
+        ReadOnlyDataSource ds = new ResourceDataSource("raw-export-failing", new ResourceSet("/", "raw-export-failing.xiidm"));
+        Network network = new XMLImporter().importData(ds, new NetworkFactoryImpl(), null);
```
Comment (rcourtier) [inline psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java]: I'm not sure why this test is necessary when there's already `exportBusWithoutInjectionInBusBreakerModelTest()` test that uses a very similar network?

Comment (marqueslanauja) [reply psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java]: I added it because it is the case prepared by the person who reported the issue. I can remove it if you'd like

File: psse/psse-converter/src/main/java/com/powsybl/psse/converter/VoltageLevelConverter.java [hunk 2]
```diff
@@ -262,11 +262,23 @@ private static void createBusBranchContextExport(VoltageLevel voltageLevel, Cont
     }
 
     private static void createBusBranchContextExportForFullExport(VoltageLevel voltageLevel, ContextExport contextExport) {
-        voltageLevel.getBusView().getBuses().forEach(bus -> contextExport.getFullExport().addBusIBusView(contextExport.getFullExport().getNewPsseBusI(), bus));
+        // If only the buses defined in BusView were considered, certain de-energized configurations could lead to terminals lacking an associated bus reference
+        voltageLevel.getConnectableStream().flatMap(connectable -> connectableBuses(voltageLevel, connectable).stream())
+                .collect(Collectors.toSet()).stream().sorted(Comparator.comparing(Identifiable::getId))
```
Comment (olperr1) [inline psse/psse-converter/src/main/java/com/powsybl/psse/converter/VoltageLevelConverter.java]: There's no need to collect and recreate another stream here:
```suggestion
                .distinct().sorted(Comparator.comparing(Identifiable::getId))
```

File: psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java (hunk 1 above)
Comment (rcourtier) [reply psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java]: I'm in favor of removing it, if that's fine with you.

Comment (marqueslanauja) [reply psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java]: Done. I've removed it
