### PR TITLE
Bug fix: when removed, network components cannot access the network anymore

### LINKED ISSUE #1960: Network still referenced from a VoltageLevel after removal
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
After removing a VoltageLevel from a network, calling `VoltageLevel::getNetwork()` on it still returns the network.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
    @Test
    public void vlRemove() {
        Network network = Network.create("test", "test");
        network.newVoltageLevel()
                .setTopologyKind(TopologyKind.BUS_BREAKER)
                .setId("bbVL")
                .setName("bbVL_name")
                .setNominalV(200.0)
                .setLowVoltageLimit(100.0)
                .setHighVoltageLimit(200.0)
                .add();
        VoltageLevel voltageLevel = network.getVoltageLevel("bbVL");
        voltageLevel.remove();
        assertNull(voltageLevel.getNetwork());
    }
```

* **What is the expected behavior?**
`VoltageLevel::getNetwork()` should return null.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by miovd**
Signed-off-by: VEDELAGO MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Fix #1960 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Bug fix

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [x] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java [hunk 1]
```diff
@@ -49,7 +50,7 @@ void addTerminal(TerminalExt terminal) {
 
     @Override
     public NetworkImpl getNetwork() {
-        return networkRef.get();
+        return Optional.ofNullable(networkRef).map(Ref::get).orElse(null);
```
Comment (flo-dup) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java:53]: One detail, isn't it less clear to create an `Optional` instead of doing the classical ternary `return x!=null ? y(x) : null`, or  of writing `if x equals null return null`?

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTerminal.java [hunk 2]
```diff
@@ -70,11 +73,14 @@ public void setNum(int num) {
...
     @Override
     public double getP() {
-        return p.get(network.get().getVariantIndex());
+        return Optional.ofNullable(network).map(n -> p.get(n.get().getVariantIndex())).orElse(Double.NaN);
     }
 
     @Override
     public Terminal setP(double p) {
+        if (network == null) {
+            throw new PowsyblException("Can not modify removed equipment");
```
Comment (flo-dup) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTerminal.java:82]: An even smaller detail, we write "cannot" in the other exceptions, but both are ok anyway

**Review by flo-dup — APPROVED** [review]
