### PR TITLE
Fix fork disconnection

### LINKED ISSUE #3236: Be able to disconnect a line from another one
### Describe the current behavior

When disconnecting a Line the graph traversal do not look for connections between two Connectable (2 lines) therfore do not disconnect themselves.

In the case of a fork like the image below if we want to disconnect the first line it is still connected to the second line.
Fork

### Describe the expected behavior

In the case of a fork like the image above if we want to disconnect the first line then it should no longer be connected to the second line. The highlighted switch should be open.

### Describe the motivation

Be able to isolate a line from another one.

### PR DESCRIPTION
**Pull request by rolnico**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
Fixes #3236

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

**Review by flo-dup — CHANGES_REQUESTED** [review]
Great!

File: iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractForkConnectDisconnectTest.java [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+
+        // D_L1 should be open but not D_L2
+        assertTrue(disconnectorL1.isOpen());
+        assertFalse(disconnectorL2.isOpen());
+    }
+
+    private void assertTerminalsStatus(List<? extends Terminal> terminals, boolean terminalsShouldBeConnected) {
+        if (terminalsShouldBeConnected) {
+            terminals.forEach(terminal -> assertNotNull(terminal.getBusView().getBus()));
+            terminals.forEach(terminal -> assertTrue(terminal.isConnected()));
```
Comment (flo-dup) [inline iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractForkConnectDisconnectTest.java:241]: these two lines are equivalent in node breaker topology (at least in the known implementations)

Comment (rolnico) [reply iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractForkConnectDisconnectTest.java:241]: yes but I preferred to make it obvious and visible since it's part of the issue

**Review by flo-dup — APPROVED** [review]
I remove the direct link to the issue as it's only solving disconnection. The connection part might also need a change.

**Review by alicecaron — APPROVED** [review]
