### PR TITLE
Correct HVDC data during CGMES import

### LINKED ISSUE #850: CGMES Conversion of HVDC
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the motivation / use case for changing the behavior?**
For CGMES networks containing HVDC, the conversion is sometimes faulty and create divergences when launching calculation on it. The conversion needs to be fixed.

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
The IIDM model may require to be modified for the conversion to be okay. This will be detailed in a future issue if needed.

### PR DESCRIPTION
**Pull request by MioRtia**
Signed-off-by: RALAMBOTIANA MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Fixes #850 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Correction of HVDC import from CGMES files

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
No

**Other information**:

### CODE REVIEW

**Comment by MioRtia** [comment]
@zamarrenolm do you agree with this way to retrieve HVDC data from CGMES files? I tested with the **SmallGridHVDC** network and it seemed to work. If you agree, I will implement the tests as well in this PR.
@annetill can you please ensure that the modifications are understandable?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 1]
```diff
@@ -11,16 +11,20 @@
...
 import com.powsybl.iidm.network.HvdcLineAdder;
+import com.powsybl.iidm.network.LccConverterStation;
 import com.powsybl.triplestore.api.PropertyBag;
 
 /**
  * @author Luma Zamarreño <zamarrenolm at aia.es>
  */
 public class DcLineSegmentConversion extends AbstractIdentifiedObjectConversion {
 
+    private static final String TARGET_PPCC = "targetPpcc";
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Leave a comment to define "targetPpcc":
// Real power injection target in the AC grid.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 2]
```diff
@@ -30,30 +34,78 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
         cconverter2 = context.dc().cgmesConverterFor(iconverter2);
     }
 
+    private void updateConverterStations(double pAC) {
+
+        // poleLossP is the active power loss at a DC Pole
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Leave a more detailed comment:
        // poleLossP is the active power loss at a DC Pole
        // for lossless operation: P(DC) = P(AC) => lossFactor = 0
        // for rectifier operation (conversion from AC to DC) with losses: P(DC) = P(AC) - poleLossP 
        // In IIDM, for rectifier operation P(DC) / P(AC) = 100 - lossFactor
        // => P(DC) / P(AC) = 1 - poleLossP / P(AC) = 1 - lossFactor / 100
        // for inverter operation (conversion from DC to AC) with losses: P(DC) = P(AC) + poleLossP 
        // In IIDM, for inverter operation P(AC) / P(DC) = 100 - lossFactor / 100
        // => P(AC) / P(DC) = 1 - poleLossP / P(DC) = 1 - poleLossP / (P(AC) + poleLossP) = 100 - lossFactor / 100

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 3]
```diff
@@ -30,30 +34,78 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
+        // for lossless operation: P(DC) = P(AC) => lossFactor = 0
+        // for rectifier operation with losses: P(DC) = P(AC) - poleLossP => P(DC) / P(AC) = 1 - poleLossP1 / P(AC) = 1 - lossFactor
+        // for inverter operation with losses: P(DC) = P(AC) + poleLossP => P(AC) / P(DC) = 1 - poleLossP / P(DC) = 1 - poleLossP / (P(AC) + poleLossP) = 1 - lossFactor
+        double poleLossP1 = cconverter1.asDouble("poleLossP");
+        double poleLossP2 = cconverter2.asDouble("poleLossP");
+
+        float lossFactor = 0;
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: I think that pAC is not the right value. I think, in the case of a good definition of pAC1 and pAC2, we should have something like that:

        double pAC1 = Double.isNaN(cconverter1.asDouble(TARGET_PPCC)) ? 0 : cconverter1.asDouble(TARGET_PPCC);
        double pAC2 = Double.isNaN(cconverter2.asDouble(TARGET_PPCC)) ? 0 : cconverter2.asDouble(TARGET_PPCC);

        float lossFactor1 = 0;
        if (decodeMode().equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && pAC1 != 0) {
            lossFactor1 = (float) (poleLossP1 / pAC1) * 100;
        } else if (decodeMode().equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER) && pAC1 + poleLossP1 != 0) {
            lossFactor1 = (float) (poleLossP1 / (pAC1 + poleLossP1)) * 100;
        }
        iconverter1.setLossFactor(lossFactor1);

        float lossFactor2 = 0;
        if (decodeMode().equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER) && pAC2 != 0) {
            lossFactor2 = (float) (poleLossP2 / Math.abs(pAC2)) * 100;
        } else if (decodeMode().equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && Math.abs(pAC2) + poleLossP2 != 0) {
            lossFactor2 = (float) (poleLossP2 / (Math.abs(pAC2) + poleLossP2)) * 100;
        }
        iconverter2.setLossFactor(lossFactor2);

But I am not sure when pAC1 or pAC2 is equal to NaN.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 4]
```diff
@@ -30,30 +34,78 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
+        updateConverterStations(pAC);
+
+        double maxP = pAC * 1.2; // arbitrary value because there is no maxP attribute in CGMES
         missing("maxP", maxP);
 
         HvdcLineAdder adder = context.network().newHvdcLine()
                 .setR(r())
                 .setNominalV(ratedUdc())
-                .setActivePowerSetpoint(p)
+                .setActivePowerSetpoint(pAC)
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: I think we have to compute P(DC) here, from pAC1/poleLossP1 or pAC2/ poleLossP2, depending on the side of the AC target value.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 5]
```diff
@@ -30,30 +34,78 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
     @Override
     public void convert() {
         Objects.requireNonNull(iconverter1);
         Objects.requireNonNull(iconverter2);
 
-        double p = activePowerSetpoint();
-        double maxP = p * 1.2;
+        double pAC1 = Double.isNaN(cconverter1.asDouble(TARGET_PPCC)) ? 0 : cconverter1.asDouble(TARGET_PPCC);
+        double pAC2 = Double.isNaN(cconverter2.asDouble(TARGET_PPCC)) ? 0 : cconverter2.asDouble(TARGET_PPCC);
+        double pAC = Math.abs(decodeMode().equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && pAC1 != 0 || pAC2 == 0 ? pAC1 : pAC2);
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: The convention saying that the active power target is defined at rectifier side is the same in the CGMES ?

Comment (annetill) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: If yes, I think that we have to write here a function to obtain the AC target value on inverter side here from the AC target value on rectifier side and the two loss factors.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 6]
```diff
@@ -30,32 +34,146 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
     }
 
+    private static double getPAc(PropertyBag p) {
+        return Double.isNaN(p.asDouble(TARGET_PPCC)) ? 0 : p.asDouble(TARGET_PPCC); // targetPpcc is the real power injection target in the AC grid in CGMES
+    }
+
+    private void updateLossFactor1(double pAC1, double poleLossP1, HvdcLine.ConvertersMode mode) {
+        if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER)) {
+            iconverter1.setLossFactor((float) (poleLossP1 / pAC1) * 100);
+        } else if (pAC1 + poleLossP1 != 0) {
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: I think we have to add in the else-if condition the fact that ````mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER)````
In this case, pAC1 is negative (inverter side), so I think that Math.abs(pAC1) is required.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 7]
```diff
@@ -30,32 +34,146 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
+            iconverter1.setLossFactor((float) (poleLossP1 / (pAC1 + poleLossP1)) * 100);
+        }
+    }
+
+    private void updateLossFactor2(double pAC2, double poleLossP2, HvdcLine.ConvertersMode mode) {
+        if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER)) {
+            iconverter2.setLossFactor((float) (poleLossP2 / Math.abs(pAC2)) * 100);
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: If side 2 is rectifier, pAC2 is positive, I think that Math.abs() is not needed.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 8]
```diff
@@ -30,32 +34,146 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
+        } else if (Math.abs(pAC2) + poleLossP2 != 0) {
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: I think we have to add in the else-if condition the fact that ````mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER)````

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 9]
```diff
@@ -30,32 +34,146 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
+        if (iconverter1.getHvdcType() == HvdcConverterStation.HvdcType.LCC) {
+            ((LccConverterStation) iconverter1).setPowerFactor(pAC1 == 0 || Double.isNaN(iconverter1.getTerminal().getQ()) ? 0.8f : (float) Math.abs(iconverter1.getTerminal().getQ() / pAC1));
+            ((LccConverterStation) iconverter2).setPowerFactor(pAC2 == 0 || Double.isNaN(iconverter2.getTerminal().getQ()) ? 0.8f : (float) Math.abs(iconverter2.getTerminal().getQ() / pAC2));
+        }
+    }
+
+    private void updateConverterStations(double pAC1, double pAC2, double poleLossP1, double poleLossP2, HvdcLine.ConvertersMode mode) {
+
+        // update loss factors
+        if (pAC1 != 0 && pAC2 != 0) {
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: I am not sure about the treatement of this condition. In this case, I think that we have to use :
- Only pAC1 if side 1 is rectifier and ignore pAC2 ;
- Only pAC2 if side 2 is rectifier and ignore pAC1.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 10]
```diff
@@ -30,32 +34,146 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
+    }
+
+    private void updatePowerFactor(double pAC1, double pAC2) {
+        if (iconverter1.getHvdcType() == HvdcConverterStation.HvdcType.LCC) {
+            ((LccConverterStation) iconverter1).setPowerFactor(pAC1 == 0 || Double.isNaN(iconverter1.getTerminal().getQ()) ? 0.8f : (float) Math.abs(iconverter1.getTerminal().getQ() / pAC1));
+            ((LccConverterStation) iconverter2).setPowerFactor(pAC2 == 0 || Double.isNaN(iconverter2.getTerminal().getQ()) ? 0.8f : (float) Math.abs(iconverter2.getTerminal().getQ() / pAC2));
+        }
+    }
+
+    private void updateConverterStations(double pAC1, double pAC2, double poleLossP1, double poleLossP2, HvdcLine.ConvertersMode mode) {
```
Comment (annetill) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: For the two else-if condition, maybe we have to add that pAC1/2 should be NaN (or 0). For me, there is a sign issue but I need our reviews. I think that when you are on inverter side, P is negative. Am I right ? And I think we have to add comments. 
````
        } else if (pAC1 != 0 && pAC2 == 0) {
            updateLossFactor1(pAC1, poleLossP1, mode);
            if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && (pAC1 - poleLossP1) != 0) {
                // pAC1 is positive.
                // lossFactor2 = poleLossP2 / pDC * 100
                // pDC = pAC1 - poleLossP1
                iconverter2.setLossFactor((float) (poleLossP2 / (pAC1 - poleLossP1)) * 100);
            } else if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER) && (Math.abs(pAC1) + poleLossP1 + poleLossP1) != 0) {
                // pAC1 is negative.
                // lossFactor2 = poleLossP2 / (pDC + poleLossP2) * 100
                // pDC = pAC1 + poleLossP1
                iconverter2.setLossFactor((float) (poleLossP2 / (Math.abs(pAC1) + poleLossP1 + poleLossP1)) * 100);
            }
        } else if (pAC2 != 0 && pAC1 == 0) {
            updateLossFactor2(pAC2, poleLossP2, mode);
            if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && (Math.abs(pAC2) + poleLossP2 + poleLossP1) != 0) {
                // pAC2 is negative.
                // lossFactor1 = poleLossP1 / pAC1 * 100
                // pAC1 = pDC + poleLossP1 = pAC2 + poleLossP2 + poleLossP1
                iconverter1.setLossFactor((float) (poleLossP1 / (Math.abs(pAC2) + poleLossP2 + poleLossP1)) * 100);
            } else if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER) && (pAC2 - poleLossP2) != 0) {
                // pAC2 is positive.
                // lossFactor1 = poleLossP1 / pDC * 100
                // pDC = pAC2 - poleLossP2
                iconverter1.setLossFactor((float) (poleLossP1 / (pAC2 - poleLossP2)) * 100);
            }
````

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 6 above)
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: pAC1's sign is **independent** of the fact of this HVDC converter station is inverter or rectifier, it is only dependent of the **side**

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 7 above)
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Same remark as above, pAC1 or pAC2 are not positive/negative depending of the stations are rectifier/inverter but if they are side 1 or 2.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 9 above)
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Maybe we should check if these two attributes are consistent ?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 10 above)
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: > For the two else-if condition, maybe we have to add that pAC1/2 should be NaN (or 0).

Sonar counts it as bad practice ("code smells") if we explicit an implied condition e.g.

```java
if (a && b) {
// do something
} else if (a) {
// first condition is false so we necessarily have a && !b, else we are in case 1
} else if (b) {
// we necessarily have !a && b, else we are in case 1
}
```
Should we willingly do a bad practice for readability ? I'm open to all answers, I'm just not sure you were aware of that.

> For me, there is a sign issue but I need our reviews. I think that when you are on inverter side, P is negative. Am I right ? And I think we have to add comments.
> 
> ```
>         } else if (pAC1 != 0 && pAC2 == 0) {
>             updateLossFactor1(pAC1, poleLossP1, mode);
>             if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && (pAC1 - poleLossP1) != 0) {
>                 // pAC1 is positive.
>                 // lossFactor2 = poleLossP2 / pDC * 100
>                 // pDC = pAC1 - poleLossP1
>                 iconverter2.setLossFactor((float) (poleLossP2 / (pAC1 - poleLossP1)) * 100);
>             } else if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER) && (Math.abs(pAC1) + poleLossP1 + poleLossP1) != 0) {
>                 // pAC1 is negative.
>                 // lossFactor2 = poleLossP2 / (pDC + poleLossP2) * 100
>                 // pDC = pAC1 + poleLossP1
>                 iconverter2.setLossFactor((float) (poleLossP2 / (Math.abs(pAC1) + poleLossP1 + poleLossP1)) * 100);
>             }
>         } else if (pAC2 != 0 && pAC1 == 0) {
>             updateLossFactor2(pAC2, poleLossP2, mode);
>             if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && (Math.abs(pAC2) + poleLossP2 + poleLossP1) != 0) {
>                 // pAC2 is negative.
>                 // lossFactor1 = poleLossP1 / pAC1 * 100
>                 // pAC1 = pDC + poleLossP1 = pAC2 + poleLossP2 + poleLossP1
>                 iconverter1.setLossFactor((float) (poleLossP1 / (Math.abs(pAC2) + poleLossP2 + poleLossP1)) * 100);
>             } else if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER) && (pAC2 - poleLossP2) != 0) {
>                 // pAC2 is positive.
>                 // lossFactor1 = poleLossP1 / pDC * 100
>                 // pDC = pAC2 - poleLossP2
>                 iconverter1.setLossFactor((float) (poleLossP1 / (pAC2 - poleLossP2)) * 100);
>             }
> ```

For sign convention, see the remarks above.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 9 above)
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Maybe we should check these two attributes are consistent?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 6 above)
Comment (annetill) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Okay, can we add a comment to explain the CGMES convention (depending on the side and not the mode of the conversion station) ?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 10 above)
Comment (annetill) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Okay, no bad practice. I understand that NaN is not used, 0 is prefered. 
Do you treat the case PAC1 = 0 and PAC2 = 0 ?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 6 above)
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: It is already commented lines 184-185:
```
        // load sign convention is used i.e. positive sign means flow out from a node
        // i.e. pAC1 >= 0 and pAC2 <= 0
```

Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: About the comment in lines 184-185: I agree on the fact that load convention is used for defining `targetPpc`, but this not implies that `pAC1 >= 0 and pAC2 <= 0`. 

In the module we are assuming (method `decodeMode`) that the user either defines explicitly the mode of operation of each converter or we try to identify which one is converter and which one is rectifier depending on the sign of `targetPpcc` at both ends.

A converter with `targetPpcc > 0` is considered a rectifier (power going out from AC network is injected into the DC line). But the `targetPpcc > 0` could be at side 1 or side 2 of the DC line.

Maybe we could add an additional check to verify that, when the mode is defined explicitly the `targetPpcc` has the expected sign. That is, if the `operatingMode` is `rectifier`, then we would expect `targetPpcc > 0`.

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java [hunk 11]
```diff
@@ -30,32 +34,146 @@ public DcLineSegmentConversion(PropertyBag l, Context context) {
...
+            }
+        } else if (pAC2 != 0) {
+            updateLossFactor2(pAC2, poleLossP2, mode);
+            if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_RECTIFIER_SIDE_2_INVERTER) && Math.abs(pAC2) - poleLossP2 != 0) {
+                iconverter1.setLossFactor((float) (poleLossP1 / (Math.abs(pAC2) - poleLossP2)) * 100);
+            } else if (mode.equals(HvdcLine.ConvertersMode.SIDE_1_INVERTER_SIDE_2_RECTIFIER) && Math.abs(pAC2) - poleLossP2 + poleLossP1 != 0) {
+                iconverter1.setLossFactor((float) (poleLossP1 / (Math.abs(pAC2) - poleLossP2 + poleLossP1)) * 100);
+            }
+        }
+
```
[the remark this answers is not in the document]
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: How would they be calculated? From the DC line's resistance?
I don't think it is worth the hassle if it is complicated to retrieve it, aren't they negligible compared to the loss between AC and DC?

[the remark this answers is not in the document]
Comment (marqueslanauja) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Losses =  I2R (R = DC line's resistance)

DC lines have low resistance so losses during transmission are typically negligible relative to the total amount of power sent.   They can be negleted and be considered later if there are IOP cases where  negleting them is not permissible.

**Comment by annetill** [comment]
We have a low test coverage with this PR. The CGMES file example with two DC lines does not covert all the cases. Do you have an idea to pass through this issue ?

**Comment by zamarrenolm** [comment]
> We have a low test coverage with this PR. The CGMES file example with two DC lines does not covert all the cases. Do you have an idea to pass through this issue ?

I think we should be able to create a modified version of the available conformity test case to prepare input data for the alternatives we are taking into account (decide the rectifier/inverter side based on the real power injection target in the AC part of the grid).

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (MioRtia) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/DcLineSegmentConversion.java]: Yesn I agree
