### PR TITLE
Fix LoadFlowParameters copy.

### LINKED ISSUE #1151: [Load flow] Parameters copy does not work with extensions
* **Do you want to request a *feature* or report a *bug*?**

Bug.

* **What is the current behavior?**

`LoadFlowParameters.copy()` does not copy extensions. For instance, the use of this in `SecurityAnalysisImpl` causes post contingency violations to not use extensions.

* **What is the expected behavior?**

A copy of parameters should have exactly the same behaviour as the original. Also, modifying the copy should not modify the original.

An easy solution will be to implement the copy by serializing and reading again the parameters, since extensions are usually serializable.

Otherwise, there is no easy technical solution for this, as extensions cannot be copied themselves.
We would need to choose if:
     - we want to support copy, and then impose that extensions must be copyable 
     - not support it and deprecate or remove the `copy` method

* **Please tell us about your environment:**
  - PowSyBl Version: 3.1.0

### PR DESCRIPTION
**Pull request by yichen88**
Copy extensions via serialize instance.
Fix usage in SecurityAnalysisImpl.

Signed-off-by: yichen88 <tang.yichenyves@gmail.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
fix #1151 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java [hunk 1]
```diff
@@ -181,7 +186,19 @@ public LoadFlowParameters setSpecificCompatibility(boolean specificCompatibility
...
+        byte[] bytes = writeInMemory();
+        try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes)) {
+            return JsonLoadFlowParameters.read(bais);
+        } catch (IOException e) {
+            throw new UncheckedIOException(e);
+        }
+    }
+
+    private byte[] writeInMemory() {
+        try (ByteArrayBuilder byteArrayBuilder = new ByteArrayBuilder()) {
```
Comment (mathbagu) [inline loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java]: Why do you use `ByteArrayBuilder`?  Why don't you use `ByteArrayOutputStream`?

File: pom.xml [hunk 2]
```diff
@@ -136,6 +136,16 @@
...
                 <version>${blazegraph.version}</version>
             </dependency>
+            <dependency>
+                <groupId>com.fasterxml.jackson.core</groupId>
+                <artifactId>jackson-core</artifactId>
+                <version>${jackson.version}</version>
+            </dependency>
+            <dependency>
+                <groupId>com.fasterxml.jackson.core</groupId>
+                <artifactId>jackson-annotations</artifactId>
```
Comment (mathbagu) [inline pom.xml]: I cannot see where this dependency is used. Is it really needed?

This dependency should be declared before jackson-core.

File: loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java (hunk 1 above)
Comment (yichen88) [reply loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java]: From doc, it seems like it is a better usage here.
> Since version 1.5, also implements OutputStream to allow efficient aggregation of output content as a byte array, similar to how ByteArrayOutputStream works, but somewhat more efficiently for many use cases.

File: pom.xml (hunk 2 above)
Comment (sylvlecl) [reply pom.xml]: The jackson-annotations and jackson-core are pulled by jackson-databind (hence the order, but we can change it).

In case we don't impose here the version used, blazegraph pulls its own version of those dependencies, which is inconsistent with our version of jackson-databind : it throws unknown methods exceptions at runtime in cgmes unit tests.

As it could happen with dependencies other than blazegraph, it's better to impose our own version of those 2 dependencies a the parent pom level.

Comment (sylvlecl) [reply pom.xml]: It's now correctly sorted!

File: loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java (hunk 1 above)
Comment (mathbagu) [reply loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java]: We could probably keep `ByteArrayBuilder` then...

**Comment by mathbagu** [comment]
@yichen88 @sylvlecl Sonar is not happy with the code coverage. Maybe we should remove the copy constructor to solve this as we know it's buggy.
What do you think?
