### PR TITLE
CGMES import: consider header info to identify profile when trying to split inputs by modelling authority

### LINKED ISSUE #3205: CGMES: use only header to identify CGMES profile instead of looking e.g. for _EQ_ in the file name
### Describe the current behavior

CGMES importer looks for `_EQ_` or `_EQ.` string presence in file name to filter for EQ profiles.

### Describe the expected behavior

A more robust solution would rather check only the model header `md:Model.profile` to determine what profile(s) a file contains.

### Describe the motivation

Got an issue with non-obvious stack trace with one IGM where files were named (allegedly weirdly):
- `confidential_EQ_confidential_EQ.xml`
- `confidential_EQ_confidential_SSH.xml`
- `confidential_EQ_confidential_SV.xml`
- `confidential_EQ_confidential_TP.xml`

All of them are then considered as `EQ`. Because they all have same `md:Model.modelingAuthoritySet` the import then fails with default importer settings.

Workarounds are:
- renaming files
- changing `iidm.import.cgmes.cgm-with-subnetworks-defined-by` to `FILENAME` (consequences may be acceptable or not)
- changing `iidm.import.cgmes.cgm-with-subnetworks` to `false` (consequences may be acceptable or not)

### Extra Information

powsybl-core 6.5.0

```
DEBUG:powsybl:Duplicate key MAS (attempted merging values [confidential_EQ_confidential_SV.xml] and [confidential_EQ_confidential_TP.xml])
java.lang.IllegalStateException: Duplicate key MAS (attempted merging values [confidential_EQ_confidential_SV.xml] and [confidential_EQ_confidential_TP.xml])
        at java.base@17.0.11/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
        at java.base@17.0.11/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
        at java.base@17.0.11/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base@17.0.11/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base@17.0.11/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base@17.0.11/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base@17.0.11/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.11/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base@17.0.11/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base@17.0.11/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base@17.0.11/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.11/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base@17.0.11/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.11/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.powsybl.cgmes.conversion.CgmesImport$MultipleGridModelChecker.separateByModelingAuthority(CgmesImport.java:260)
        at com.powsybl.cgmes.conversion.CgmesImport$MultipleGridModelChecker.separate(CgmesImport.java:247)
        at com.powsybl.cgmes.conversion.CgmesImport.importData(CgmesImport.java:163)
        at com.powsybl.iidm.network.Network.read(Network.java:128)
        at com.powsybl.iidm.network.Network.read(Network.java:135)
        at com.powsybl.python.network.NetworkCFunctions.lambda$loadNetwork$6(NetworkCFunctions.java:171)
        at com.powsybl.python.commons.Util.doCatch(Util.java:132)
        at com.powsybl.python.network.NetworkCFunctions.loadNetwork(NetworkCFunctions.java:163)
```

### PR DESCRIPTION
**Pull request by zamarrenolm**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #3205 

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

When analysing inputs for CGMES import potentially corresponding to different modelling authorities, the EQ instance files were identified from its filename.
This could lead to potential problems if filenames did not follow the right pattern.

**What is the new behavior (if this is a feature change)?**

When analysing inputs for CGMES import potentially corresponding to different modelling authorities, the EQ instance files are identified from the `profile` attribute inside the `FullModel` header contents.

A non-related unit test resource has been fixed because it contained a wrong profile (it was an SSH instance file declaring a profile of Equipment): `tap-changer/invalidLtcFlag_SSH.xml`.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
Comment (rcourtier) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:1]: There are 2 spellings of the same word: "modeling" and "modelling". It seems that both are valid: modeling would be the US form, whereas modelling would be the EN one, but for consistency I would prefer to keep only one form.
Since CGMES defines the "modeling authority", I think we should stick to that spelling. Could you please change the "modelling" occurences to "modeling"?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java [hunk 1]
```diff
@@ -358,6 +391,11 @@ private String readModelingAuthority(InputStream is) throws XMLStreamException {
                     reader.close();
                 }
             }
+            // We may have read a modelling authority,
+            // but if we haven't been able to check that one the profiles checks ok we discard it
```
Comment (rcourtier) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java]:
```suggestion
            // but if we haven't been able to check that one of the profiles checks ok we discard it
```

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:1]: change applied

**Review by rcourtier — APPROVED** [review]

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java [hunk 2]
```diff
@@ -319,37 +325,64 @@ private Set<ReadOnlyDataSource> separateByModelingAuthority() {
...
                     int token = reader.next();
-                    if (token == XMLStreamConstants.START_ELEMENT && reader.getLocalName().equals(CgmesNames.MODELING_AUTHORITY_SET)) {
-                        modellingAuthority = reader.getElementText();
-                        stopReading = true;
-                    } else if (token == XMLStreamConstants.END_ELEMENT && reader.getLocalName().equals(CgmesNames.FULL_MODEL)) {
+                    if (isStartModelingAuthority(reader, token)) {
+                        modelingAuthority = reader.getElementText();
+                        if (profileChecked) {
+                            stopReading = true;
+                        }
```
Comment (olperr1) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:389]: If the element text is stored in `modelingAuthority` only when `profileChecked` is true, the final test can be removed:

```java
var text = reader.getElementText();
if (profileChecked) {
    modelingAuthority = text;
    stopReading = true;
}
```

and
```patch
- // We may have read a modeling authority,
- // but if we haven't been able to check that one of the profiles checks ok we discard it
- if (!profileChecked) {
-    modelingAuthority = null;
- }
```

**Review by olperr1 — CHANGES_REQUESTED** [review]

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java (hunk 2 above)
Comment (zamarrenolm) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:389]: We do not know the order in which the elements will come (modeling authority then profiles or first the profiles),
so we always have to keep the modeling authority until we read both data, then decide if it is accepted or not

Comment (olperr1) [reply cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java:389]: Oh, you are right! I missed this point.

**Review by rcourtier — APPROVED** [review]
