### PR TITLE
Replace simulShunt in LoadFlowParameters by shuntCompensatorVoltageControlOn

### LINKED ISSUE #1929: LoadFlowParameters simulShunt
* **Do you want to request a *feature* or report a *bug*?**

A improvement indeed.

* **What is the current behavior?**

In `LoadFlowParameters`, when we want to activate shunt's voltage control, the parameter to use is `simulShunt`. But this term is not really explicit compared to `transformerVoltageControlOn` or `phaseShifterRegulationOn`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

I propose to change `simulShunt` for `shuntVoltageControlOn`.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by miovd**
Signed-off-by: VEDELAGO MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Yes. Fix #1929 

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
Yes
- [x] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

### CODE REVIEW

File: loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java [hunk 1]
```diff
@@ -354,7 +372,7 @@ public BalanceType getBalanceType() {
                 .put("noGeneratorReactiveLimits", noGeneratorReactiveLimits)
                 .put("phaseShifterRegulationOn", phaseShifterRegulationOn)
                 .put("twtSplitShuntAdmittance", twtSplitShuntAdmittance)
-                .put("simulShunt", simulShunt)
+                .put("simulShunt", shuntCompensatorVoltageControlOn)
```
Comment (flo-dup) [inline loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java:375]: you could also replace the key here

**Review by flo-dup — APPROVED** [review]

**Review by annetill — APPROVED** [review]
