### PR TITLE
check voltage level on both side of the line

### LINKED ISSUE #1242: [UCTE] Lines should have the same nominal voltage at each side
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
If a UCTE line is defined between two buses with different nominal voltages, the import works properly but it's an error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Try to import a UCTE file with this kind of line:
```
ABCDEF61 AGHIJK31 1 0 0.5770 1.0950 7.576000    67
```

* **What is the expected behavior?**
An exception should be thrown. The ENTSO-E Quality of dataset indicates:
> Both line connectivity nodes must have the same voltage level, i.e. the same 7th character.

The error should be thrown by the `fix()` method, so you have to override this method in the UcteLine class to check that the 7th characters of each nodes are the same.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by jlabous**
Signed-off-by: Jérémy LABOUS <jlabous@silicom.fr>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
fix #1242

### CODE REVIEW

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java [hunk 1]
```diff
@@ -399,6 +399,9 @@ private static void createLines(UcteNetworkExt ucteNetwork, Network network) {
         for (UcteLine ucteLine : ucteNetwork.getLines()) {
             UcteNodeCode nodeCode1 = ucteLine.getId().getNodeCode1();
             UcteNodeCode nodeCode2 = ucteLine.getId().getNodeCode2();
+            if (!nodeCode1.getVoltageLevelCode().equals(nodeCode2.getVoltageLevelCode())) {
+                throw new UcteException("Line with two different nominal voltages");
+            }
```
Comment (mathbagu) [inline ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java:404]: I think this test should be done in the `UcteElement::fix` method.
@murgeyseb what do you think?
@jlabous You should give more information in the error message: with your proposal, if this exception is thrown, I don't know which line is the faulty one so it's impossible to debug/fix it.

File: ucte/ucte-converter/src/test/resources/differentLinesVoltage.uct [hunk 2]
```diff
@@ -0,0 +1,12 @@
+##C 2007.05.01
+Test case for UCTE import issue in PowSyBl core package
+contact : sebastien.murgey@rte-france.com
```
Comment (mathbagu) [inline ucte/ucte-converter/src/test/resources/differentLinesVoltage.uct:3]: Do not copy/paste test cases, but adapt it to the situation.

File: ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java (hunk 1 above)
Comment (murgeyseb) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java:404]: Yes it could be done in UcteElement::fix, it is true. And the message should be more explicit.
But this method is supposed to fix the issue, not throw exception, but why not.

Comment (mathbagu) [reply ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java]: So maybe we can do the test in the constructor then?
