### PR TITLE
PrintBalanceSummary with a Writer as parameter (the other is deprecated)

### LINKED ISSUE #756: Don't use a logger in parameters of Networks.printBalanceSummary
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
The balance summary can only appear in a logger in debug.

* **What is the expected behavior?**
The balance summary could be written anywhere using a `Writer` as a parameter (in a file, console output, etc).

* **What is the motivation / use case for changing the behavior?**
There is no real reason why the balance summary  should only appear in a logger in debug, a user should be able to retrieve it whereever they want.

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0-SNAPSHOT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by MioRtia**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Fixes #756 

**Other information:**
The "new" behaviour of `Networks.printBalanceSummary(String, Network, Logger)` is not exactly the same as before but it is quite equivalent.

### CODE REVIEW

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java [hunk 1]
```diff
@@ -92,7 +93,38 @@ public static void runScript(Network network, Reader reader, Writer out) {
...
+    public static void printBalanceSummary(String title, Network network, Logger logger) throws IOException {
+        try (OutputStream os = new OutputStream() {
+            private String mem = "";
+            private boolean closed = false;
+
+            @Override
+            public void write(int i) {
+                byte[] bytes = new byte[1];
+                bytes[0] = (byte) (i & 0xff);
+                mem = mem + new String(bytes);
```
Comment (jonenst) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java]: This is bad because it's quadratic no ?

**Comment by jonenst** [comment]
Can't we just use a StringWriter instead of manually implementing an outpustream ?

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java (hunk 1 above)
Comment (geofjamg) [reply iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java]: What is the purpose of this custom outputstream overriding?

File: iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java [hunk 2]
```diff
@@ -25,32 +23,28 @@
...
-                     "| Shunt at nom V (MVar) | 0.0 0.0 (0) | 0.0 0.0 (0)      | 0.0 0.0 (0) | 0.0 0.0 (0)        |\n" +
-                     "+-----------------------+-------------+------------------+-------------+--------------------+" + System.lineSeparator(),
-                buffer.toString());
+    public void printBalanceSummaryTest() throws IOException {
+        try (Writer writer = new StringWriter()) {
+            Network network = EurostagTutorialExample1Factory.createWithMultipleConnectedComponents();
+            Networks.printBalanceSummary("", network, writer);
+            assertEquals("Active balance at step '':" + System.lineSeparator() +
+                            "+-----------------------+--------------------------------+----------------------------------+\n" +
+                            "|                       | Main CC connected/disconnected | Others CC connected/disconnected |\n" +
```
Comment (geofjamg) [inline iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java]: Any reason to not use System.lineSeparator() here ?

Comment (MioRtia) [reply iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java]: Not really, it was from the former code. I changed it in my last commit

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java [hunk 3]
```diff
@@ -295,25 +313,23 @@ private static String writeInTable(ConnectedPower balanceMainCC, ConnectedPower
...
-    private static void logOtherCC(Logger logger, String title, Supplier<String> tableSupplier, ConnectedPower balanceOtherCC) {
-        if (logger.isDebugEnabled()) {
-            logger.debug("Active balance at step '{}':\n{}", title, tableSupplier.get());
-        }
+    private static void logOtherCC(Writer writer, String title, Supplier<String> tableSupplier, ConnectedPower balanceOtherCC) throws IOException {
+        writer.write("Active balance at step '" + title + "':" + System.lineSeparator() + tableSupplier.get());
 
         if (!balanceOtherCC.connectedLoads.isEmpty()) {
-            logger.trace("Connected loads in other CC: {}", balanceOtherCC.connectedLoads);
+            writer.write("Connected loads in other CC: " + String.join(", ", balanceOtherCC.connectedLoads) + System.lineSeparator());
```
Comment (mathbagu) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java]: I don’t understand why you use String.join here instead of concat the value.

Is it more efficient to call several times the write method instead of concat the different part of the string?

File: iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java [hunk 4]
```diff
@@ -25,32 +23,28 @@
...
-                     "| Generation (MW)       | 607.0       | 0.0              | 0.0         | 0.0                |\n" +
-                     "| Shunt at nom V (MVar) | 0.0 0.0 (0) | 0.0 0.0 (0)      | 0.0 0.0 (0) | 0.0 0.0 (0)        |\n" +
-                     "+-----------------------+-------------+------------------+-------------+--------------------+" + System.lineSeparator(),
-                buffer.toString());
+    public void printBalanceSummaryTest() throws IOException {
+        try (Writer writer = new StringWriter()) {
+            Network network = EurostagTutorialExample1Factory.createWithMultipleConnectedComponents();
+            Networks.printBalanceSummary("", network, writer);
+            assertEquals("Active balance at step '':" + System.lineSeparator() +
+                            "+-----------------------+--------------------------------+----------------------------------+" + System.lineSeparator() +
```
Comment (mathbagu) [inline iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java]: Be careful, the API we use to render ASCII tables doesn’t handle properly the line separator. It uses \n even on windows. It explains why the compilation fails

File: iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java (hunk 2 above)
Comment (MioRtia) [reply iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java]: After investigation, it was because ASCII tables do not handle line separators correctly

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java (hunk 3 above)
Comment (MioRtia) [reply iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java]: In terms of efficiency, I don't think there is a big difference between the two ways... I'm going back to concatenation to obtain the same output as before.
