### PR TITLE
iIDM v1.14: Remove fixed tap phase tap changer mode

### LINKED ISSUE #3344: Remove the phase tap changer FIXED_TAP regulation mode
### Describe the current behavior

A `PhaseTapChanger` regulation mode can be set among the three following ones: `FIXED_TAP`, `CURRENT_LIMITER`, `ACTIVE_POWER_CONTROL`.

### Describe the expected behavior

A `PhaseTapChanger` regulation mode can be set among the two following ones: `CURRENT_LIMITER`, `ACTIVE_POWER_CONTROL`, if not an error should be thrown.

To assure the retro compatibility on previous versions, when a phase tap changer is imported with a `FIXED_TAP` regulation mode awarning message is logged and a regulation mode by default should be set (discuss which one, or a `null` `RegulationMode` is acceptable?).

### Describe the motivation

A regulation mode in `FIXED_TAP` usages are similar to the a non regulating `PhaseTapChanger`. This information is already represented with the `regulating` boolean. This mode induces confusion in the possible combinations of the (`regulationMode`, `regulating`) attributes couples.

### Extra Information

`PhaseShifterSetAsFixedTap` and `PhaseShifterShiftTap` modifications will only set the `PhaseTapChanger` `regulating` value to `false` and set the tap position as given.

### PR DESCRIPTION
**Pull request by alicecaron**
:warning: **Adaptation would be needed when merging this PR with #3438.**

<br/>

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #3344 

**Does this PR introduce a breaking change or deprecate an API?**
- [X] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [X] The *Breaking Change* or *Deprecated* label has been added
- [X] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

***For all:***
Phase tap changer regulation mode `RegulationMode.FIXED_TAP` was removed.

Retro compatibility exists to still handle older IIDM versioned files (<1.14) with FIXED_TAP mode. The mode in IIDM will then be CURRENT_LIMITER with regulating=false so an import/export round trip with FIXED_TAP regulation mode at the beginning will fail but functionnally there should be no impact.

If you used `FIXED_TAP` mode:
- to disable the regulation on an already existing phase tap changer, you should call `phaseTapChanger.setRegulating(false)` instead.
- to initialize a phase tap changer, you should set regulating to false, and use another regulation mode (default one is `CURRENT_LIMITER`).

***And for custom IIDM implementations' maintainers:***
Custom IIDM implementations' maintainers should change the default `regulationMode` value to `CURRENT_LIMITER` in their `PhaseTapChangerAdder`'s implementations.

### CODE REVIEW

File: iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java [hunk 1]
```diff
@@ -175,10 +176,29 @@ protected static void writePhaseTapChanger(String name, PhaseTapChanger ptc, Net
...
         readTapChangerAttributes(adder, context);
 
-        PhaseTapChanger.RegulationMode regulationMode = context.getReader().readEnumAttribute(ATTR_REGULATION_MODE, PhaseTapChanger.RegulationMode.class);
+        // Set regulation according to IIDM version
+        IidmSerDeUtil.runUntilMaximumVersion(IidmVersion.V_1_13, context, () -> {
+            adder.setRegulationMode(null);
+            if (context.getReader() instanceof BinReader) {
+                adder.setRegulationMode(context.getReader().readEnumAttribute(ATTR_REGULATION_MODE, PhaseTapChanger.RegulationMode.class));
+            } else {
+                String readRegulationMode = context.getReader().readStringAttribute(ATTR_REGULATION_MODE);
```
Comment (alicecaron) [inline iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java:185]: Add unit test to ensure older IIDM versions can still be read with `FIXED_TAP` regulation mode (even if it will be exported as `CURRENT_LIMITER` and `regulating=false`

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java [hunk 2]
```diff
@@ -312,15 +301,9 @@ private PhaseTapChanger.RegulationMode getPtcRegulatingMode(boolean ltcFlag,
...
+        // we avoid regulation by setting regulating to false
 
-        // rca.regulationMode has been initialized to FIXED_TAP
-
-        PhaseTapChanger.RegulationMode finalRegulationMode = PhaseTapChanger.RegulationMode.FIXED_TAP;
-        if (ltcFlag) {
-            finalRegulationMode = regulationMode;
-        }
-        return finalRegulationMode;
+        return ltcFlag && regulating;
```
Comment (alicecaron) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java:306]: @rcourtier is this handling correctly the ltcFlag/regulating control with CGMES?

File: cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java [hunk 3]
```diff
@@ -867,7 +867,7 @@ private static <C extends Connectable<C>> void writePhaseTapChanger(C eq, PhaseT
             // We reset the phase tap changer type stored in the extensions
             String typeTabular = CgmesNames.PHASE_TAP_CHANGER_TABULAR;
             CgmesExportUtil.setCgmesTapChangerType(eq, tapChangerId, typeTabular);
-            boolean ltcFlag = obtainPhaseTapChangerLtcFlag(ptc.getRegulationMode());
+            boolean ltcFlag = ptc.isRegulating();
```
Comment (alicecaron) [inline cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java:870]: @rcourtier is this handling correctly the ltcFlag/regulating control with CGMES?

File: iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java [hunk 4]
```diff
@@ -175,10 +176,29 @@ protected static void writePhaseTapChanger(String name, PhaseTapChanger ptc, Net
     protected static void readPhaseTapChanger(String name, PhaseTapChangerAdder adder, Terminal terminal, NetworkDeserializerContext context) {
         readTapChangerAttributes(adder, context);
 
-        PhaseTapChanger.RegulationMode regulationMode = context.getReader().readEnumAttribute(ATTR_REGULATION_MODE, PhaseTapChanger.RegulationMode.class);
+        // Set regulation according to IIDM version
+        IidmSerDeUtil.runUntilMaximumVersion(IidmVersion.V_1_13, context, () -> {
+            adder.setRegulationMode(null);
+            if (context.getReader() instanceof BinReader) {
```
Comment (alicecaron) [inline iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java:182]: @olperr1 I had some trouble with the code below when the round trip used the BinReader => I think something should be done in the `BinReader::readStringAttribute` method that does not handle correctly this case. No problem for other formats (Json, Xml)

File: iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/PhaseShifterTest.java [hunk 5]
```diff
@@ -87,7 +87,7 @@ void testHasImpactShiftTap() {
 
         twoWindingsTransformer.getPhaseTapChanger().setRegulationMode(PhaseTapChanger.RegulationMode.ACTIVE_POWER_CONTROL);
```
Comment (olperr1) [inline iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/PhaseShifterTest.java]: Can you remove this line?
`modification4` has no impact on the network because the tap is already at the maximum tap position, therefore it cannot be raised from 1.
Having this line makes the test harder to understand.

File: iidm/iidm-serde/src/test/resources/V1_13/terminalRef.xiidm [hunk 6]
```diff
@@ -40,15 +40,15 @@
             </iidm:ratioTapChanger>
         </iidm:twoWindingsTransformer>
         <iidm:twoWindingsTransformer id="VLY643" r="0.04724999999999999" x="4.049724365620455" g="0.0" b="0.0" ratedU1="400.0" ratedU2="158.0" bus1="VL41" connectableBus1="VL41" voltageLevelId1="VL4" bus2="VL61" connectableBus2="VL61" voltageLevelId2="VL6">
-            <iidm:phaseTapChanger lowTapPosition="0" tapPosition="1" regulationMode="FIXED_TAP" regulationValue="200.0">
+            <iidm:phaseTapChanger lowTapPosition="0" tapPosition="1" regulationMode="ACTIVE_POWER_CONTROL" regulationValue="200.0" regulating="false">
```
Comment (olperr1) [inline iidm/iidm-serde/src/test/resources/V1_13/terminalRef.xiidm]: Why not `CURRENT_LIMITER` as in the other versions' `terminalRef.xiidm`?

File: iidm/iidm-serde/src/test/resources/V1_0/phaseShifterRoundTripRef.xml [hunk 7]
```diff
@@ -15,7 +15,7 @@
             </iidm:busBreakerTopology>
         </iidm:voltageLevel>
         <iidm:twoWindingsTransformer id="PS1" r="2.0" x="100.0" g="0.0" b="0.0" ratedU1="380.0" ratedU2="380.0" bus1="B1" connectableBus1="B1" voltageLevelId1="VL1" bus2="B3" connectableBus2="B3" voltageLevelId2="VL3" p1="50.08403" q1="29.201416" p2="-50.042015" q2="-27.100708">
-            <iidm:phaseTapChanger lowTapPosition="0" tapPosition="1" targetDeadband="10.0" regulationMode="FIXED_TAP" regulationValue="200.0">
+            <iidm:phaseTapChanger lowTapPosition="0" tapPosition="1" targetDeadband="10.0" regulationMode="CURRENT_LIMITER" regulationValue="200.0" regulating="true">
```
Comment (olperr1) [inline iidm/iidm-serde/src/test/resources/V1_0/phaseShifterRoundTripRef.xml]: Why not `regulating="false"`?
(Same remark for the other versions' `phaseShifterRoundTripRef.xml`.)

File: iidm/iidm-serde/src/test/resources/V1_13/terminalRef.xiidm (hunk 6 above)
Comment (alicecaron) [reply iidm/iidm-serde/src/test/resources/V1_13/terminalRef.xiidm]: done

File: iidm/iidm-serde/src/test/resources/V1_0/phaseShifterRoundTripRef.xml (hunk 7 above)
Comment (alicecaron) [reply iidm/iidm-serde/src/test/resources/V1_0/phaseShifterRoundTripRef.xml]: done

File: cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java [hunk 8]
```diff
@@ -1030,21 +1030,27 @@ void phaseTapChangerTapChangerControlEQTest() throws IOException {
...
+            eq = getEQ(network, baseName, tmpDir, exportParams);
+            testTcTccWithAttribute(eq, "_PS1_PTC_RC", "_PS1_PT_T_2", "currentFlow");
 
             // PST local with ACTIVE_POWER_CONTROL
             network = PhaseShifterTestCaseFactory.createLocalActivePowerWithTargetDeadband();
+            assertFalse(network.getTwoWindingsTransformer("PS1").getPhaseTapChanger().isRegulating());
             eq = getEQ(network, baseName, tmpDir, exportParams);
             testTcTccWithAttribute(eq, "_PS1_PTC_RC", "_PS1_PT_T_2", "activePower");
-            network.getTwoWindingsTransformer("PS1").getPhaseTapChanger().setRegulating(true);
+            network.getTwoWindingsTransformer("PS1").getPhaseTapChanger().setRegulating(false);
```
Comment (olperr1) [inline cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java]: Can you restore the previous line?
`regulating` is already false (see assertion 3 lines before). Therefore, this has no effect and the following of this "paragraph" doesn't test anything new in this case.

**Review by olperr1 — APPROVED** [review]

**Review by olperr1 — CHANGES_REQUESTED** [review]
Can you fix the 5 intentionality sonar issues?
