### PR TITLE
Delete node count

### LINKED ISSUE #781: Clarify graph API regarding vertex indices and its use in node breaker topology
* **Do you want to request a *feature* or report a *bug*?**

API improvement.

* **What is the current behavior?**

See PR #775:
the node breaker topology uses the `UndirectGraph` interface to represent the topology. When creating it, it starts by setting a "node count" before actually adding those nodes.
A problem arises when nodes indices are not contiguous, for example after removing some equipments. In that  case, the index of some vertices can overflow the allocated array.
The PR fixes this by ensuring that the array is extended in that case, but the node breaker API remains ambiguous.

* **What is the expected behavior?**

The API must be clarified:
    - Are vertices indices required to be contiguous ?
    - Should the setNodeCount method be deleted, considered as handled by the graph implementation? Otherwise, what should it do ? If only allocation with a "guess", rename it ? If we remove it, should we add a method to ensure memory efficiency once the voltage level is "stabilized" ? (compact)

* **What is the motivation / use case for changing the behavior?**

Clarify the API to avoid bugs when using it, for example by underallocating vertices, or by looping on vertices indices from 0 to N whereas they are not contiguous.

* **Please tell us about your environment:**
PowSyBl Version: 2.5.0-SNAPSHOT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

Follows bug fix in PR #775 .

### LINKED ISSUE #1118: Delete nodeCount attribute of NodeBreakerView network
* **Do you want to request a *feature* or report a *bug*?**
Evolution? but it will also solve a bug

* **What is the current behavior?**
When a `Connectable` is removed from a voltage level, the vertex is removed if it is isolated. When we export the network to an XML, and import the file, the `nodeCount` can be lesser than the index of a vertex. Then, an exception is thrown.

* **What is the expected behavior?**
The `nodeCount` attribute will be deleted (not present anymore in the XIIDM file.

* **What is the motivation / use case for changing the behavior?**
This attribute was supposed to be used to allocate a certain amount of vertices but it is not so useful in the end... Deleting it would solve the issue.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by MioRtia**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?**
fix #781 
fix #1118 

**What kind of change does this PR introduce?**
Bug fix

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [x] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:
In this proposition, I kept the same behaviour for `NodeBreakerVoltageLevel.cleanTopology()` than `NodeBreakerVoltageLevel.clean()` used to have **with the same issues**: hence, when the topology is cleaned and intermediate nodes are removed, they cannot be used again e.g. if a node/breaker voltage level only used nodes 1, 2 and 4 and is cleaned, attempting to use node 3 will throw a `PowsyblException` with the message `Vertex 3 not found`. Is this the behavior we want?

### CODE REVIEW

File: iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java [hunk 1]
```diff
@@ -21,6 +21,8 @@
  */
 public final class IidmXmlUtil {
 
+    private static final String FOR_IIDM_XML_VERSION = " for IIDM-XML version ";
```
Comment (mathbagu) [inline iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java]: Create a complete message instead and use it in Message.format()

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java [hunk 2]
```diff
@@ -872,13 +863,23 @@ private void checkTerminal(TerminalExt terminal) {
...
     }
 
+    private void addNodes(int node) {
+        int oldCount = graph.getVertexCount();
+        if (node >= oldCount) {
+            for (int i = oldCount; i < node + 1; i++) {
+                graph.addVertex();
+            }
+        }
+    }
```
Comment (mathbagu) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java]: I'm not sure it's what we discussed. Adding a vertex will create a terminal. The idea is to create a terminal only if you need to attach something. As you remove the call to `clean()`, the unnecessary terminals are not removed.

It's compliant with the current version of powsybl, but I thought we wanted to go further.

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java [hunk 3]
```diff
@@ -166,6 +166,8 @@ public Switch add() {
             }
             SwitchImpl aSwitch = new SwitchImpl(NodeBreakerVoltageLevel.this, id, getName(), kind, open, retained, fictitious);
             getNetwork().getIndex().checkAndAdd(aSwitch);
+            addNodes(node1);
```
Comment (mathbagu) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java]: I think I will rename this method to `reserveNodes` or `ensureNode`. The **s** in the name of the method seems strange for someone who reads the code. You have to go in the implementation to understand why you put an **s**.

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java [hunk 4]
```diff
@@ -757,7 +752,7 @@ public void detach(final TerminalExt terminal) {
     }
 
     @Override
-    public void clean() {
+    public void cleanTopology() {
```
Comment (mathbagu) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java]: Maybe we could keep the name of the old method?

**Comment by mathbagu** [comment]
@MioRtia I think it's strange to not be able to reuse a vertex. How can I replace an injection by another? If it's supported by the API (remove + add), it's OK for me to keep it like this

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java (hunk 2 above)
Comment (MioRtia) [reply iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java]: Okay, I was not really sure about the conclusion of what had been decided last time... If we want to create a vertex only each time a Terminal is created, we might not need a `clean` method (the vertex will be deleted when not used and created again if reused).

**Comment by MioRtia** [comment]
> @MioRtia I think it's strange to not be able to reuse a vertex. How can I replace an injection by another? If it's supported by the API (remove + add), it's OK for me to keep it like this

With this proposition, when an injection (for example) is removed and another replaces it, there is no issue. There is an issue however, when `cleanTopology` is called between the two actions. I'm wondering how useful should this method be? As I said above, if we don't want to create "superfluous" vertices, it can be deleted (it will avoid most of issues I think).

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java [hunk 5]
```diff
@@ -358,20 +358,28 @@
...
+         *
+         * @deprecated Depending on your use case, use {@link #getMaximumNodeIndex()} or {@link #getNodeCapacity()}.
          */
-        int getNodeCount();
+        @Deprecated
+        default int getNodeCount() {
+            throw new UnsupportedOperationException();
+        }
+
+        default int getMaximumNodeIndex() {
```
Comment (mathbagu) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java]: Please add Javadoc on this method to well understand what is expected

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java [hunk 6]
```diff
@@ -358,20 +358,28 @@
...
+            throw new UnsupportedOperationException();
+        }
+
+        default int getNodeCapacity() {
```
Comment (mathbagu) [inline iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java]: Please add Javadoc on this method to well understand what is expected

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java [hunk 7]
```diff
@@ -647,6 +653,21 @@ public int getNode2() {
                     });
         }
 
+        @Override
+        public void removeInternalConnections(int node1, int node2) {
+            int[] internalConnectionsToBeRemoved = Arrays.stream(graph.getEdges())
+                    .filter(e -> graph.getEdgeObject(e) == null)
+                    .filter(e -> graph.getEdgeVertex1(e) == node1 && graph.getEdgeVertex2(e) == node2)
```
Comment (mathbagu) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java]: I think you should also get edges between node2 and node1 (the graph is not directed)

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java [hunk 8]
```diff
@@ -49,6 +56,10 @@
      */
     int getVertexCount();
 
+    default int getMaximumVertexIndex() {
```
Comment (mathbagu) [inline math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java]: Add a Javadoc also there

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java [hunk 9]
```diff
@@ -129,6 +129,24 @@ public int addVertex() {
         return v;
     }
 
+    @Override
+    public void addVertexIfNotPresent(int v) {
+        if (v < vertices.size()) {
+            if (removedVertices.contains(v)) {
```
Comment (mathbagu) [inline math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java]: Are you sure this is efficient: should we store the removedVertices in another container (ordered) like a set?

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java [hunk 10]
```diff
@@ -129,6 +129,24 @@ public int addVertex() {
...
+                vertices.set(v, new Vertex<>());
+                removedVertices.remove(v);
+            }
+        } else {
+            for (int i = vertices.size(); i < v; i++) {
+                vertices.add(null);
+                removedVertices.add(i);
```
Comment (mathbagu) [inline math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java]: Maybe we should also rename `removedVertices` to availableVertices`

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java [hunk 11]
```diff
@@ -149,11 +167,29 @@ public V removeVertex(int v) {
         return obj;
     }
 
+    private void cleanVertices(int v) {
+        vertices.remove(v);
+        removedVertices.remove(v);
+        if (removedVertices.contains(v - 1)) {
+            cleanVertices(v - 1);
+        }
```
Comment (mathbagu) [inline math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java]: I'm not sure it is really effecient to have a recursion here where a for-loop looks OK

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java [hunk 12]
```diff
@@ -149,11 +167,29 @@ public V removeVertex(int v) {
...
 
+    @Override
+    public int getMaximumVertexIndex() {
+        for (int i = vertices.size(); i > 0; i--) {
+            if (!removedVertices.contains(i - 1)) {
+                return i - 1;
+            }
+        }
+        return -1;
+    }
```
Comment (mathbagu) [inline math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java]: I'm not sure to understand what this method does:
`if (!removedVertices.contains(i - 1))` seems equivalent to `if (vertices.at(i) != null` ?

Is it really possible to have null vertices at the end of the list. The cleanVertices should avoid that situation?

Comment (MioRtia) [reply math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java]: Yes, this was coded before I thought of doing `cleanVertices`, i will modify it

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java (hunk 8 above)
Comment (MioRtia) [reply math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java]: In the end I deleted the method since it basically `getVertexCapacity() - 1`

File: iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java (hunk 6 above)
Comment (MioRtia) [reply iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java]: At the end, I deleted this method since it always returns `getMaximumNodeIndex() + 1`. It was useful before having `cleanVertices`.

File: math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java (hunk 12 above)
Comment (MioRtia) [reply math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java]: At the end, I deleted this method as it is redundant with `getNodeCapacity`
