### PR TITLE
BBranch calculated connectable bus from NB view can be null

### LINKED ISSUE #939: getConnectableBus() returns exception if there is not bus in voltage level
* **Do you want to request a *feature* or report a *bug*?**
Bit of both

* **What is the current behavior?**
From a node breaker network, if there is a voltage level without bus, getConnectableBus() returns an exception "should not happen".

* **What is the expected behavior?**
To be defined: should we accept null if no bus is found? Or should we create a fictitious bus in this case? If so, how do we discriminate fictitious bus from real ones?

* **What is the motivation / use case for changing the behavior?**
It makes the import of the CGMES files of some contries to fail.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.0.0-SNAPSHOT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### LINKED ISSUE #981: connectableBus throws exception in topology calculated from node-breaker all switches open
* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Exception is thrown when `BusView` of a `Terminal` is queried for `calculatedBus` in some situations.
Specifically: the voltage level has topology kind of node-breaker and all switches are opened. In this situation no bus is calculated, and the search for a `calculatedBus` fails, throwing an exception.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
A minimal example has been created as a unit test case in the branch `issue_nb_connectableBus` (module `iidm-impl`, class `NodeBreakerTest`, method `issueConnectableBus`). The following graph shows the export of the voltage level topology:

Screen Shot 2019-10-15 at 23 02 19

* **What is the expected behavior?**
A bus should be calculated in the voltage level. If no bus is calculated by design, then `null` could be a valid return value from the method `connectableBus`.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.0.0-SNAPSHOT
  - OS Version: *

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
It seems the current behavior is related to change in commit 0e2578716fc913b0d8e7f779278dc5316a201d44 where the condition for throwing the exception was changed (fixed).

### PR DESCRIPTION
**Pull request by MioRtia**
Signed-off-by: RALAMBOTIANA MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
fix #981 
fix #939

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java [hunk 1]
```diff
@@ -401,8 +401,8 @@ BusExt getConnectableBus(int node) {
             // if nothing found, just take the first bus
             if (connectableBus2[0] == null) {
                 Iterator<CalculatedBus> it = getBuses().iterator();
```
Comment (geofjamg) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java]: I don't remember why the original check is done using iterator but as getBuses() returns a Collection it would be more clear to use isEmpty()

Comment (zamarrenolm) [reply iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java]: agree on using `isEmpty`
