### PR TITLE
Fix NPE in network validation

### LINKED ISSUE #3186: Network validation: NPE when trying to set minimum acceptable level in an invalidated network
### Describe the current behavior

A network is created with minimum accepted validation level set to `EQUIPMENT`.
Later, the network is updated with steady state data.
An attempt to set minimum accepted level to `STEADY_STATE_HYPOTHESIS` is made. It is expected that the request is accepted.
Instead, a null pointer exception (NPE) is raised.

Code to reproduce the error:
```java
Network network = Network.create("test", "iidm");
network.setMinimumAcceptableValidationLevel(ValidationLevel.EQUIPMENT);
VoltageLevel vl = network.newSubstation().setId("s1").add()
        .newVoltageLevel().setId("vl1").setNominalV(100).setTopologyKind(TopologyKind.NODE_BREAKER).add();
Load l1 = vl.newLoad().setId("l1").setNode(0).add();

// Check the validation level after all equipment has been defined
assertEquals(ValidationLevel.EQUIPMENT, network.getValidationLevel());

// Update the network with steady state data
l1.setP0(10.0);
l1.setQ0(1.0);

// Try to raise the minimum validation level
network.setMinimumAcceptableValidationLevel(ValidationLevel.STEADY_STATE_HYPOTHESIS);
assertEquals(ValidationLevel.STEADY_STATE_HYPOTHESIS, network.getValidationLevel());
```

The error output is:

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at com.powsybl.iidm.network.ValidationUtil.validate(ValidationUtil.java:750)
	at com.powsybl.iidm.network.impl.NetworkImpl.setMinimumAcceptableValidationLevel(NetworkImpl.java:1266)
```

### Describe the expected behavior

The error is provoked by the first lines in the method for `NetworkImpl::setMinimumAcceptableValidationLevel`:

```java
@Override
public Network setMinimumAcceptableValidationLevel(ValidationLevel validationLevel) {
    Objects.requireNonNull(validationLevel);
    if (this.validationLevel == null) {
        this.validationLevel = ValidationUtil.validate(Collections.unmodifiableCollection(index.getAll()), false, false, this.validationLevel, ReportNode.NO_OP);
    }
    ...
```

When `this.validationLevel` is `null` (the actual calculated level has been invalidated by some change), the validation util is called with a `null` value in the parameter for "previous" validation level.

One way to solve it is to consider the "previous" validation level as the minimum one, instead of the actual one:
 
```java
@Override
public Network setMinimumAcceptableValidationLevel(ValidationLevel validationLevel) {
    Objects.requireNonNull(validationLevel);
    if (this.validationLevel == null) {
        ValidationLevel previous = this.minValidationLevel;
        this.validationLevel = ValidationUtil.validate(Collections.unmodifiableCollection(index.getAll()), false, false, previous, ReportNode.NO_OP);
    }
    ...
```

### Describe the steps

_No response_

### Environment

PowSyBl version 6.5.0.

### Relevant Log Output

_No response_

### Extra Information

This suggestion is made in the context of CGMES import refactoring to split the conversion of networks in two stages:

1. Building the network structure from equipment (EQ) files that contain only connectivity and electric characteristics of the devices.
2. Apply information from a steady state hypothesis (SSH) file.

During the first stage we want to keep validation level at `EQUIPMENT`. After SSH data has been applied to the network, we want to raise the minimum validation level to `STEADY_STATE_HYPOTHESIS`, and report any missing data from the checks.

### PR DESCRIPTION
**Pull request by zamarrenolm**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Fixes #3186

### CODE REVIEW

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java [hunk 1]
```diff
@@ -1262,7 +1262,8 @@ public ValidationLevel getValidationLevel() {
     public Network setMinimumAcceptableValidationLevel(ValidationLevel validationLevel) {
         Objects.requireNonNull(validationLevel);
         if (this.validationLevel == null) {
-            this.validationLevel = ValidationUtil.validate(Collections.unmodifiableCollection(index.getAll()), false, false, this.validationLevel, ReportNode.NO_OP);
+            ValidationLevel previous = this.minValidationLevel;
+            this.validationLevel = ValidationUtil.validate(Collections.unmodifiableCollection(index.getAll()), false, false, previous, ReportNode.NO_OP);
```
Comment (olperr1) [inline iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java:1266]: I suggest to use `getValidationLevel()` here instead. It would highlight the intention:

```java
    @Override
    public Network setMinimumAcceptableValidationLevel(ValidationLevel minLevel) {
        Objects.requireNonNull(minLevel);
        ValidationLevel currentLevel = getValidationLevel();
        if (currentLevel.compareTo(minLevel) < 0) {
            throw new ValidationException(this, "Network should be corrected in order to correspond to validation level " + minLevel);
        }
        this.minValidationLevel = minLevel;
        return this;
    }
```

The variables were also renamed to increase readability.

**Review by olperr1 — CHANGES_REQUESTED** [review]

File: iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java (hunk 1 above)
Comment (zamarrenolm) [reply iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java]: implemented your suggestion

Comment (olperr1) [reply iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java]: Thanks @zamarrenolm!

**Review by olperr1 — APPROVED** [review]
