### PR TITLE
Base bus-branch export problems detection on connectables' terminals

### LINKED ISSUE #3676: Failing to export some voltage level in bus/branch
### Describe the current behavior

When exporting in bus/branch, some connectable buses can be null but so when the voltage level is exported as bus/branch it fails.

### Describe the expected behavior

When exporting in bus/branch, check if all the terminals of the voltage level's connectables have a "connectableBusId" to allow to  export the voltage level in bus/branch. If not export in initial topology or throw error depending on the export option.

### PR DESCRIPTION
**Pull request by olperr1**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #3676

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

The bus-branch export problem detection introduced by #3623 consider that the export of a voltage level is problematic only if all its switches are open. But in some cases, the export can be invalid for a voltage level even when some of its switches are closed (for instance, when there is a coupling switch closed).

**What is the new behavior (if this is a feature change)?**
The detection relies on the terminals of the voltage level's connectables. When at least one of these terminals have a null "connectableBusId", the export is considered as invalid.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/util/TopologyLevelUtil.java [hunk 1]
```diff
@@ -36,36 +34,41 @@ public static TopologyLevel determineTopologyLevel(VoltageLevel vl, NetworkSeria
...
      *
      * @param vl the voltage level being exported
      * @param context the serialization context
      * @param topologyLevel the requested topology level for export
      * @return the topology level that should be used for export
-     * @throws PowsyblException if exporting a BUS_BRANCH topology while all switches are open and the configured behavior is THROW_EXCEPTION
+     * @throws PowsyblException When the topology to check is BUS_BRANCH, an export problem is detected, and the configured behavior is THROW_EXCEPTION.
      */
     private static TopologyLevel checkVoltageLevelExportTopology(VoltageLevel vl, NetworkSerializerContext context, TopologyLevel topologyLevel) {
+        if (topologyLevel == TopologyLevel.BUS_BRANCH) {
```
Comment (rolnico) [inline iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/util/TopologyLevelUtil.java]: You can probably merge two if:

```java
    private static TopologyLevel checkVoltageLevelExportTopology(VoltageLevel vl, NetworkSerializerContext context, TopologyLevel topologyLevel) {
        if (topologyLevel == TopologyLevel.BUS_BRANCH
            && vl.getConnectableStream()
                .map(Connectable::getTerminals)
                .flatMap(List<Terminal>::stream)
                .anyMatch(t -> t.getBusView().getConnectableBus() == null)) {
            if (context.getOptions()
                    .getBusBranchVoltageLevelIncompatibilityBehavior() == ExportOptions.BusBranchVoltageLevelIncompatibilityBehavior.THROW_EXCEPTION) {
                throw new PowsyblException("Cannot export voltage level \"" + vl.getId() + "\" in BUS_BRANCH topology: this would lead to an invalid IIDM.");
            }
            return TopologyLevel.valueOf(vl.getTopologyKind().name());
        }
        return topologyLevel;
    }
```

Comment (olperr1) [reply iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/util/TopologyLevelUtil.java]: Thanks, I applied your suggestion.

**Review by rolnico — APPROVED** [review]
LGTM
